- samples/Office365Groups/README.md
- samples/Office365Groups/apiProperties.json
> Added README.md for Office365 Groups connector

- connectors/MicrosoftGraphSecurity/apiProperties.json
- connectors/MicrosoftGraphSecurity/apidefinition.swagger.json
> Microsoft Graph Security Connector

- connectors/Plumsail Documents/apiDefinition.swagger.json
- connectors/Plumsail Documents/apiProperties.json
- connectors/Plumsail Forms/apiDefinition.swagger.json
- connectors/Plumsail Forms/apiProperties.json
- connectors/Plumsail HelpDesk/apiDefinition.swagger.json
- connectors/Plumsail HelpDesk/apiProperties.json
- connectors/Plumsail SP/apiDefinition.swagger.json
- connectors/Plumsail SP/apiProperties.json
Hello, please consider the ability to merge my changes with adding Plumsail connectors.
> Add Plumsail connectors

- samples/AzureKeyVault/apiProperties.json
> Added redirect mode.

- connectors/Encodian/apiDefinition.swagger.json
- connectors/Encodian/apiProperties.json
> Added Encodian Connector Files

- connectors/WebMerge/apiDefinition.swagger.json
- connectors/WebMerge/apiProperties.json
> add WebMerge connector

- connectors/ahead/apiDefinition.swagger.json
- connectors/ahead/apiProperties.json
> added ahead connector files

- connectors/Yeelight/apiDefinition.swagger.json
- connectors/Yeelight/apiProperties.json
> Added Yeelight connector

- connectors/Rencore/apiDefinition.swagger.json
- connectors/Rencore/apiProperties.json
> Added the Rencore connector

- connectors/Encodian/apiDefinition.swagger.json
> Added Schemes

- connectors/Stormboard/apiDefinition.swagger.json
- connectors/Stormboard/apiProperties.json
> Adds Stormboard connector

- connectors/MicrosoftGraphSecurity/apiProperties.json
- connectors/MicrosoftGraphSecurity/apidefinition.swagger.json
> Adding triggers to MicrosoftGraphSecurity connector

- connectors/Encodian/apiDefinition.swagger.json
- connectors/Encodian/apiProperties.json
- connectors/WebMerge/apiDefinition.swagger.json
- connectors/WebMerge/apiProperties.json
- connectors/ahead/apiDefinition.swagger.json
- connectors/ahead/apiProperties.json
> Doc update

- samples/IdealPostcodes/README.md
- samples/IdealPostcodes/apiDefinition.swagger.json
- samples/IdealPostcodes/apiProperties.json
This PR includes
- Authentication fix (removed user_token definition)
- Wording updates and added MS Open API extensions for actions
- Added Readme file for sample usage
---
> Ideal Postcodes Update and Readme

- connectors/ModuleQ/apiDefinition.swagger.json
- connectors/ModuleQ/apiProperties.json
> add ModuleQ connector

- connectors/AzureAD/Readme.md
- connectors/AzureAD/apiDefinition.swagger.json
- connectors/AzureAD/apiProperties.json
> Open sourced Azure AD connector

- connectors/Mitto/apiDefinition.swagger.json
- connectors/Mitto/apiProperties.json
> Added Mitto connector

- connectors/MicrosoftGraphSecurity/apiProperties.json
Changing the triggers to use the field "lastModifiedDateTime"
---
> Trigger update for MicrosoftGraphSecurity

- samples/Facebook/README.md
- samples/Facebook/apiDefinition.swagger.json
- samples/Facebook/apiProperties.json
> Updating facebook sample

- pipelines/buildcli.yml
Add component governance build
> Add component governance build

- pipelines/buildcli.yml
Integration of security tools.
> Security tools

- connectors/AzureAD/apiDefinition.swagger.json
Removed sample email and sample password
> Removed sample email and sample password

- connectors/D7SMS/Readme.md
- connectors/D7SMS/apiDefinition.swagger.json
- connectors/D7SMS/apiProperties.json
> Add D7SMS Connector

- connectors/D7SMS/apiDefinition.swagger.json
> [D7SMS] Updated datatype of the destination mobile number

- connectors/CognitiveServicesTextAnalytics/Readme.md
- connectors/CognitiveServicesTextAnalytics/apiDefinition.swagger.json
- connectors/CognitiveServicesTextAnalytics/apiProperties.json
> Open Sourced Text Analytics connector

- connectors/Planner/Readme.md
- connectors/Planner/apiDefinition.swagger.json
- connectors/Planner/apiProperties.json
> Open Sourced Planner connector

- .vscode/settings.json
- use swagger schema for apiDefinition.swagger.json files.
- set some default json formatting settings.
---
> Add VS Code integration

- connectors/Planner/apiDefinition.swagger.json
- connectors/Planner/apiProperties.json
> "DeleteTask" action was added to Planner.

- tools/paconn-cli/README.md
- tools/paconn-cli/setup.py
- Update readme.md
- Fix installation dependency on azure-storage-blob. (Issue #86) 
---
> Fix paconn-cli

- samples/AcuityScheduling/README.md
- samples/AcuityScheduling/apiDefinition.swagger.json
- samples/AcuityScheduling/apiProperties.json
> Acuity Scheduling Sample Connector

- connectors/exghts/apiDefinition.swagger.json
- connectors/exghts/apiProperties.json
- connectors/exghts/readme.md
> exghts - generate documents and more

- connectors/Cloudmersive Virus Scan/apiDefinition.swagger.json
- connectors/Cloudmersive Virus Scan/apiProperties.json
- connectors/Cloudmersive Virus Scan/readme.md
Added Connector source for [Cloudmersive Virus Scan Connector](https://docs.microsoft.com/en-us/connectors/cloudmersive/)
---
> Added Cloudmersive Virus Scan Connector

- connectors/FireText/apiDefinition.swagger.json
- connectors/FireText/apiProperties.json
- connectors/FireText/readme.md
> Initial add of FireText Connector

- connectors/Cloudmersive Image Processing/apiDefinition.swagger.json
- connectors/Cloudmersive Image Processing/apiProperties.json
- connectors/Cloudmersive Image Processing/readme.md
> Added Cloudmersive Image Processing Connector

- connectors/Aquaforest PDF Connector/apiDefinition.swagger.json
- connectors/Aquaforest PDF Connector/apiProperties.json
- connectors/Aquaforest PDF Connector/readme.md
First commit of Aquaforest PDF Connector
---
> Aquaforest PDF Connector

- connectors/Cloudmersive Data Validation/apiDefinition.swagger.json
- connectors/Cloudmersive Data Validation/apiProperties.json
- connectors/Cloudmersive Data Validation/readme.md
> Added Cloudmersive Data Validation Connector

- connectors/Smarp/apiDefinition.swagger.json
- connectors/Smarp/apiProperties.json
- connectors/Smarp/readme.md
> Smarp connector

- connectors/JungleMail365/apiDefinition.swagger.json
- connectors/JungleMail365/apiProperties.json
- connectors/JungleMail365/readme.md
> Added JungleMail 365 connector files

- connectors/ShareEffect/apiDefinition.swagger.json
- connectors/ShareEffect/apiProperties.json
- connectors/ShareEffect/readme.md
As requested, the PR with our connector.
---
> ShareEffect connector

- connectors/HotProfile/apiDefinition.swagger.json
- connectors/HotProfile/apiProperties.json
- connectors/HotProfile/readme.md
> HotProfile PR

- connectors/Tallyfy/apiDefinition.swagger.json
- connectors/Tallyfy/apiProperties.json
- connectors/Tallyfy/readme.md
> Add Tallyfy connector

- connectors/InSpark Company Connect/apiDefinition.swagger.json
- connectors/InSpark Company Connect/apiProperties.json
- connectors/InSpark Company Connect/readme.md
Adds the InSpark Company Connect connector to the open source repository of Power Platform Connectors.
---
> Add InSpark Company Connect connector

- connectors/Rencore Governance/apiDefinition.swagger.json
- connectors/Rencore Governance/apiProperties.json
- connectors/Rencore Governance/readme.md
Added the Rencore Governance connector
> Added the Rencore Governance connector

- connectors/Serverless360/apiDefinition.swagger.json
- connectors/Serverless360/apiProperties.json
- connectors/Serverless360/readme.md
> Added Serverless360 Folder

- connectors/Scrive eSign/apiDefinition.swagger.json
- connectors/Scrive eSign/apiProperties.json
- connectors/Scrive eSign/readme.md
> Add Scrive eSign connector files

- tools/paconn-cli/paconn/commands/download.py
> Added missing connector id

- tools/paconn-cli/paconn/__init__.py
- tools/paconn-cli/setup.py
> Increased version to 0.0.12

- connectors/LeadDesk/apiDefinition.swagger.json
- connectors/LeadDesk/apiProperties.json
- connectors/LeadDesk/readme.md
> LeadDesk connector submission

- connectors/SignRequest/apiDefinition.swagger.json
- connectors/SignRequest/apiProperties.json
- connectors/SignRequest/readme.md
Added SignRequest connector files as requested. 
For more information see: [https://signrequest.com/api/v1/docs/](https://signrequest.com/api/v1/docs/)
> Add SignRequest connector files

- connectors/PartnerCenterReferrals/apiDefinition.swagger.json
- connectors/PartnerCenterReferrals/apiProperties.json
- connectors/PartnerCenterReferrals/readme.md
Added Partner Center Referrals connector and associated files under connectors folder
---
> Adding Partner Center Referrals connector.

- connectors/Witivio/apiDefinition.swagger.json
- connectors/Witivio/apiProperties.json
- connectors/Witivio/readme.md
> adding witivio connector

- connectors/Scrive eSign/apiDefinition.swagger.json
- connectors/Scrive eSign/apiProperties.json
> Update connector files for new auth method.

- connectors/Mtarget SMS/apiDefinition.swagger.json
- connectors/Mtarget SMS/apiProperties.json
- connectors/Mtarget SMS/readme.md
> Uploading MTarget's connector

- samples/AzureKeyVault/Readme.md
> AzureKeyVault - Update brand names

- connectors/Slascone/apiDefinition.swagger.json
- connectors/Slascone/apiProperties.json
- connectors/Slascone/readme.md
> add slascone

- connectors/KnowledgeLakeRPA/apiDefinition.swagger.json
- connectors/KnowledgeLakeRPA/apiProperties.json
- connectors/KnowledgeLakeRPA/readme.md
> Creation of knowledgelake rpa connector repo

- README.md
> Added readme requirement to open source

- connectors/DBF2XML/apiDefinition.swagger.json
- connectors/DBF2XML/apiProperties.json
- connectors/DBF2XML/readme.md
> Publish db2xml connector

- .github/CODEOWNERS
> Update code owners to be current

- certified-connectors/emfluencemp/apiDefinition.swagger.json
> emfluencemp - update version, add titles

- certified-connectors/CandidateZip/apiDefinition.swagger.json
- certified-connectors/CandidateZip/apiProperties.json
- certified-connectors/CandidateZip/readme.md
Submitting Cerified Connector artifects for Candidate Zip
---
> Submitting Cerified Connector artifects for Candidate Zip

- certified-connectors/JotForm Enterprise/apiDefinition.swagger.json
- certified-connectors/JotForm Enterprise/apiProperties.json
- certified-connectors/JotForm Enterprise/readme.md
> Adding JotForm connector

- certified-connectors/Aquaforest PDF Connector/apiDefinition.swagger.json
- certified-connectors/Aquaforest PDF Connector/readme.md
> Aquaforest - Updating brand names

- certified-connectors/CloudAppSecurity/apiDefinition.swagger.json
> CloudAppSecurity - Updating brand names

- certified-connectors/PartnerCenterReferrals/readme.md
> [PartnerCenterReferrals] Updating the outdated brand names

- certified-connectors/gofileroom/readme.md
> [GoFileRoom] Updating outdated brand names

- certified-connectors/CompanyConnect/readme.md
> [CompanyConnect] Updating outdated brand names

- certified-connectors/Mtarget SMS/readme.md
> [Mtarget] Updating outdated brand names

- certified-connectors/JungleMail365/readme.md
> [JungleMail365] Updating outdated brand names

- certified-connectors/ElfsquadProductConfigurator/README.md
- certified-connectors/ElfsquadProductConfigurator/apiDefinition.swagger.json
> [Elfsquad] Updating outdated brand names

- certified-connectors/ShortURL/apiDefinition.swagger.json
- certified-connectors/ShortURL/readme.md
> [ShortURL] Updating the outdated brand names

- certified-connectors/easyvistaselfhelp/readme.md
> [EasyVistaSelfHelp] Updating outdated brand names

- certified-connectors/D7SMS/Readme.md
> [D7SMS] Updating outdated brand names

- certified-connectors/DBF2XML/readme.md
> [DBF2XML] Updating outdated brand names

- certified-connectors/exghts/readme.md
> [Exghts] Updating the outdated brand names

- certified-connectors/Plumsail SP/readme.md
> [PlumsailSP] Updating the outdated brand names

- certified-connectors/Scrive eSign/readme.md
> [ScriveeSign] Updating the outdated brand names

- certified-connectors/Serverless360/readme.md
> [Serverless360] Updating the outdated brand names

- certified-connectors/SignRequest/readme.md
> [SignRequest] Updating the outdated brand names

- certified-connectors/Tallyfy/readme.md
> [Tallyfy] Updating the updated brand names

- certified-connectors/Witivio/readme.md
> [Witivio] Updating the outdated brand names

- certified-connectors/Telephony-Xtended-Service/readme.md
> [TelephonyXtendedServ] Updating the outdated brand names

- certified-connectors/Cloudmersive Data Validation/readme.md
- certified-connectors/Cloudmersive Document Conversion/Readme.md
- certified-connectors/Cloudmersive Image Processing/readme.md
- certified-connectors/Cloudmersive Virus Scan/readme.md
> [Cloudmersive Connectors] Updating outdated brand names

- certified-connectors/Solyp/apiDefinition.swagger.json
- certified-connectors/Solyp/apiProperties.json
- certified-connectors/Solyp/readme.md
Changes for SOLYP connector certification.
> Solyp connector

- certified-connectors/OutlookTasks/apiDefinition.swagger.json
- certified-connectors/OutlookTasks/apiProperties.json
- certified-connectors/OutlookTasks/readme.md
Adding the OutlookTasks connector with operations that are safe to open-source.
> [OutlookTasks] Open-sourcing the OutlookTasks connector

- certified-connectors/TractionGuest/apiDefinition.swagger.json
- certified-connectors/TractionGuest/apiProperties.json
- certified-connectors/TractionGuest/readme.md
This PR adds a folder "TractionGuest" to the Certified Connectors folder. It includes the apiDefinitions and apiProperties files as well as a readme.
> Included Traction Guest into Certified Connectors.

- certified-connectors/AzureAD/apiDefinition.swagger.json
> Add support for $skip in the List group members

- custom-connectors/SAP-ODATA-Demo/Readme.md
> Adding a link to the CLI tool in Readme.md

- certified-connectors/Tilkee/README.md
- certified-connectors/Tilkee/apiDefinition.swagger.json
- certified-connectors/Tilkee/apiProperties.json
Certification team just certified our connector 🙂
> Adding Tilkee certified connector

- certified-connectors/AzureAD/apiDefinition.swagger.json
- certified-connectors/AzureAD/apiProperties.json
> Enabled paging for GetGroupMembers and removed redundant test values

- README.md
[Readme] Updated Azure Key Vault URL
> [Readme] Updated Azure Key Vault URL

- certified-connectors/TRIGGERcmd/README.md
- certified-connectors/TRIGGERcmd/apiDefinition.swagger.json
- certified-connectors/TRIGGERcmd/apiProperties.json
Added the api json files
Added the README.md file
---
> Initial commit

- certified-connectors/Tilkee/apiDefinition.swagger.json
- certified-connectors/Tilkee/apiProperties.json
After testing it in Preview mode, we decided to make some adjustement to our connector.
> [Tilkee] Updating our connector

- certified-connectors/Connect2All/apiDefinition.swagger.json
- certified-connectors/Connect2All/apiProperties.json
- certified-connectors/Connect2All/readme.md
> Connect2All

- certified-connectors/OpenText ContentServer by One Fox/apiDefinition.swagger.json
- certified-connectors/OpenText ContentServer by One Fox/apiProperties.json
- certified-connectors/OpenText ContentServer by One Fox/readme.md
> First version of the OpenText ContentServer connector by One Fox

- certified-connectors/Blackbaud Raiser's Edge NXT/apiDefinition.swagger.json
- certified-connectors/Blackbaud Raiser's Edge NXT/apiProperties.json
- certified-connectors/Blackbaud Raiser's Edge NXT/readme.md
> added Blackbaud Raiser's Edge NXT connector

- certified-connectors/Industrial App Store/README.MD
- certified-connectors/Industrial App Store/apiDefinition.swagger.json
- certified-connectors/Industrial App Store/apiProperties.json
Added Inudstrial App Store (IAS) connector.
---
> IAS-connector-add

- certified-connectors/Cloudmersive Barcode/apiDefinition.swagger.json
- certified-connectors/Cloudmersive Barcode/apiProperties.json
- certified-connectors/Cloudmersive Barcode/readme.md
> Added Cloudmersive Barcode Connector

- certified-connectors/Tilkee/apiDefinition.swagger.json
Some updates about our Webhook routes.
> [TILKEE] Update certified connector

- certified-connectors/CivicPlus/README.md
- certified-connectors/CivicPlus/apiDefinition.swagger.json
- certified-connectors/CivicPlus/apiProperties.json
> add CivicPlus Connector

- certified-connectors/OneBlink/README.md
- certified-connectors/OneBlink/apiDefinition.swagger.json
- certified-connectors/OneBlink/apiProperties.json
> add OneBlink Connector

- certified-connectors/MicrosoftGraphSecurity/apidefinition.swagger.json
> [MicrosoftGraphSecurity] Remove 'contact' placeholder in swagger.

- certified-connectors/LMS365/Readme.md
- certified-connectors/LMS365/apiDefinition.swagger.json
- certified-connectors/LMS365/apiProperties.json
> add LMS365 connector

- certified-connectors/Eduframe/Readme.md
- certified-connectors/Eduframe/apiDefinition.swagger.json
- certified-connectors/Eduframe/apiProperties.json
Add the Eduframe connector
---
> [Eduframe] Open-sourcing the Eduframe connector

- certified-connectors/Huddle/apiDefinition.swagger.json
- certified-connectors/Huddle/apiProperties.json
- certified-connectors/Huddle/readme.md
Commits the Huddle Power Platform Connector to the Open Source repo
---
> Huddle Open Sourcing

- certified-connectors/MicrosoftGraphSecurity/apidefinition.swagger.json
> [MicrosoftGraphSecurity] Fix unicode chars

- certified-connectors/PartnerCenterReferrals/apiDefinition.swagger.json
- certified-connectors/PartnerCenterReferrals/readme.md
> [Partner Center Referral] Added fields and headers to update api

- certified-connectors/LIFX/apiDefinition.swagger.json
- certified-connectors/LIFX/apiProperties.json
- certified-connectors/LIFX/readme.md
> Initial LIFX connector

- certified-connectors/JotForm Enterprise/apiProperties.json
Only Icon brand color & icon changed.
---
> Icon brand color & icon changed

- certified-connectors/Otto.bot/apiDefinition.swagger.json
- certified-connectors/Otto.bot/apiProperties.json
- certified-connectors/Otto.bot/readme.md
> [Otto.bot] Publish Certified Connector

- certified-connectors/timeghost/README.md
- certified-connectors/timeghost/apiDefinition.swagger.json
- certified-connectors/timeghost/apiProperties.json
add timeghost certified connector
---
> [timeghost] Certified connector publishing

- certified-connectors/TractionGuest/apiDefinition.swagger.json
> Updating the apiDefinitions.swagger.json for Traction Guest.

- certified-connectors/Telephony-Xtended-Service/apiDefinition.swagger.json
> Updated host url

- certified-connectors/Blackbaud Raiser's Edge NXT/apiDefinition.swagger.json
> New edit custom field actions; misc designer edits

- certified-connectors/AzureIoTCentral/README.md
- certified-connectors/AzureIoTCentral/apiDefinition.swagger.json
- certified-connectors/AzureIoTCentral/apiProperties.json
PR to add the Azure IoT Central certified connector.
> Adding Azure IoT Central certified connector

- certified-connectors/Tallyfy/apiDefinition.swagger.json
- certified-connectors/Tallyfy/apiProperties.json
> Tallyfy Connector V2

- certified-connectors/Encodian/Readme.md
- certified-connectors/Encodian/apiDefinition.swagger.json
> Encodian May 20 Release

- certified-connectors/Cloudmersive NLP/Readme.md
- certified-connectors/Cloudmersive NLP/apiDefinition.swagger.json
- certified-connectors/Cloudmersive NLP/apiProperties.json
> Added Cloudmersive NLP Connector

- certified-connectors/Motimate/Readme.md
- certified-connectors/Motimate/apiDefinition.swagger.json
- certified-connectors/Motimate/apiProperties.json
> Added Motimate as a certified connector.

- certified-connectors/HouseRaterQA/apiDefinition.swagger.json
- certified-connectors/HouseRaterQA/apiProperties.json
- certified-connectors/HouseRaterQA/readme.md
> HouseRaterQA Connector

- certified-connectors/AzureAD/apiDefinition.swagger.json
Fixed typo in swagger for AzureAD.
---
> [AzureAD] fix metadata

- custom-connectors/AcuityScheduling/README.md
- custom-connectors/AzureKeyVault/Readme.md
- custom-connectors/SAP-ODATA-Demo/Readme.md
Fixed spelling in custom connectors.
---
> Fixed spelling

- tools/paconn-cli/README.md
- tools/paconn-cli/paconn/__init__.py
- tools/paconn-cli/paconn/authentication/auth.py
- tools/paconn-cli/paconn/authentication/tokenmanager.py
- tools/paconn-cli/paconn/commands/commands.py
- tools/paconn-cli/paconn/commands/logout.py
- tools/paconn-cli/paconn/commands/params.py
- tools/paconn-cli/paconn/operations/download.py
- tools/paconn-cli/paconn/operations/json_keys.py
- tools/paconn-cli/setup.py
Included publisher metadata in the connector download and added a new command for logout.
> Publisher whitelist

- certified-connectors/WorkSpan/apiDefinition.swagger.json
- certified-connectors/WorkSpan/apiProperties.json
- certified-connectors/WorkSpan/readme.md
WorkSpan connector Version v1.0.0
---
> WorkSpan Connector for Power Automate

- certified-connectors/PartnerCenterReferrals/apiDefinition.swagger.json
- certified-connectors/PartnerCenterReferrals/apiProperties.json
> [Partner Center Referrals] Added patch api

- certified-connectors/Scrive eSign/apiDefinition.swagger.json
- certified-connectors/Scrive eSign/apiProperties.json
- certified-connectors/Scrive eSign/readme.md
Updates open source documentation for Scrive eSign conenctor.
---
> Scrive eSign: add Set File action

- certified-connectors/CPQSync/apiDefinition.swagger.json
- certified-connectors/CPQSync/apiProperties.json
- certified-connectors/CPQSync/readme.md
> Added the official CPQSync Connector

- certified-connectors/Vantage 365 Barcodes/apiDefinition.swagger.json
- certified-connectors/Vantage 365 Barcodes/apiProperties.json
- certified-connectors/Vantage 365 Barcodes/readme.md
> Added Vantage 365 Bar Codes connector

- certified-connectors/Pure Leads/apiDefinition.swagger.json
- certified-connectors/Pure Leads/apiProperties.json
- certified-connectors/Pure Leads/readme.md
> Added Pure Leads Connector

- certified-connectors/PIPware KPIs/README.md
- certified-connectors/PIPware KPIs/apiDefinition.swagger.json
- certified-connectors/PIPware KPIs/apiProperties.json
> Add PIPware KPIs artifacts

- certified-connectors/NetDocuments/apiDefinition.swagger.json
- certified-connectors/NetDocuments/apiProperties.json
- certified-connectors/NetDocuments/readme.md
> Update NetDocuments connector

- schemas/apiDefinition.swagger.schema.json
- schemas/paconn-apiProperties.schema.json
Added support for a more fuller set of extensions supported in the Power Platform's swagger files along with apiProperties.
> [VS Code] Update json schemas for apiProperties.json and apiDefinition.swagger.json

- certified-connectors/smsapi/Readme.md
- certified-connectors/smsapi/apiDefinition.swagger.json
- certified-connectors/smsapi/apiProperties.json
> smsapi.com init

- certified-connectors/Cloudmersive File Processing/Readme.md
- certified-connectors/Cloudmersive File Processing/apiDefinition.swagger.json
- certified-connectors/Cloudmersive File Processing/apiProperties.json
> Added Cloudmersive File Processing Connector

- pipelines/validate_connector.yml
> Azure pipelines test

- pipelines/validate_connector.yml
> Update validate_connector.yml for Azure Pipelines

- certified-connectors/Office365GroupsMail/apiDefinition.swagger.json
- certified-connectors/Office365GroupsMail/apiProperties.json
- certified-connectors/Office365GroupsMail/readme.md
Adding the following operations to the open source repo:
- `ListConversations`
- `GetGroupConversation`
- `ListConversationThreads`
- `ListGroupThreads`
- `GetConversationThread`
- `DeleteConversationThread`
- `ListThreadPosts`
- `GetThreadPost`
- `GetAttachments`
- `ListGroups`
---
> [Office365GroupsMail] Open source connector

- custom-connectors/RecordedFuture/README.md
- custom-connectors/RecordedFuture/apiDefinition.swagger.json
- custom-connectors/RecordedFuture/apiProperties.json
Commit during the certification process
---
> Recorded Future Custom Connector

- certified-connectors/PDF Blocks/apiDefinition.swagger.json
- certified-connectors/PDF Blocks/apiProperties.json
- certified-connectors/PDF Blocks/readme.md
> Add PDF Blocks connector artifacts

- custom-connectors/Instagram/README.md
- custom-connectors/Instagram/apiDefinition.swagger.json
- custom-connectors/Instagram/apiProperties.json
Open sourcing Instagram connector created by Microsoft team.
> Adding Instagram

- custom-connectors/AzureADPhoneMethods/Readme.md
- custom-connectors/AzureADPhoneMethods/apiDefinition.swagger.json
- custom-connectors/AzureADPhoneMethods/apiProperties.json
> Initial release

- README.md
> Bezhan oss ccp integration

- certified-connectors/AzureIoTCentral/apiDefinition.swagger.json
> Updating Azure IoT Central connector

- certified-connectors/OpenText eDOCS by One Fox/apiDefinition.swagger.json
- certified-connectors/OpenText eDOCS by One Fox/apiProperties.json
- certified-connectors/OpenText eDOCS by One Fox/readme.md
> OpenText eDOCS by One Fox version 1

- certified-connectors/PIPware KPIs/apiDefinition.swagger.json
We are just changing our support address
---
> Change support address

- certified-connectors/Muhimbi PDF Converter Online/apiDefinition.swagger.json
- certified-connectors/Muhimbi PDF Converter Online/apiProperties.json
- certified-connectors/Muhimbi PDF Converter Online/readme.md
> Swagger files for Muhimbi PDF converter services online

- certified-connectors/Poka/Readme.md
- certified-connectors/Poka/apiDefinition.swagger.json
- certified-connectors/Poka/apiProperties.json
> Adding a certified connector for Poka

- certified-connectors/Connect2All/apiDefinition.swagger.json
- certified-connectors/Connect2All/apiProperties.json
Re-created this pull request as requested to merge into master.
Changed Icon to new brand icon.
Added properties for new required metadata.
> Connect2 all

- certified-connectors/AtBot/README.md
- certified-connectors/AtBot/apiDefinition.swagger.json
- certified-connectors/AtBot/apiProperties.json
> AtBot Connector Info Submitted

- certified-connectors/Ticketing.events/apiDefinition.swagger.json
- certified-connectors/Ticketing.events/apiProperties.json
- certified-connectors/Ticketing.events/readme.md
- certified-connectors/Ventipix Asset and Inventory Manager/apiDefinition.swagger.json
- certified-connectors/Ventipix Asset and Inventory Manager/apiProperties.json
- certified-connectors/Ventipix Asset and Inventory Manager/readme.md
> New connectors

- tools/paconn-cli/README.md
> Added stackOwner limitation for Paconn

- certified-connectors/FORCAM FORCE Bridge/Readme.md
- certified-connectors/FORCAM FORCE Bridge/apiDefinition.swagger.json
- certified-connectors/FORCAM FORCE Bridge/apiProperties.json
Initial commit for FORCAM FORCE Bridge Connector
---
> Add FORCAM FORCE Bridge connector artifacts

- certified-connectors/Planner/apiDefinition.swagger.json
- certified-connectors/Planner/apiProperties.json
This PR resolves the current top-voted ideas in the ideas forum:
- https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Include-Checklist-Within-Planner-Task-When-Created-in-Flow/idi-p/36367
- https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Planner-Get-more-task-details/idi-p/72538
- https://powerusers.microsoft.com/t5/Power-Automate-Ideas/New-Planner-Action-Move-Task/idi-p/71623
- https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Add-Categories-Labels-Tags-to-Planner-Task/idi-p/85439
Incidentally - these items should already be closed:
- https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Update-the-Planner-Description-field/idi-p/35314
- https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Planner-attach-document-from-Outlook-email/idi-p/50047
---
This …
> Add functionality to the Planner connector

- certified-connectors/Encodian/apiDefinition.swagger.json
- certified-connectors/Encodian/apiProperties.json
> Encodian July 20 Release

- certified-connectors/AXtension Content Gate/apiDefinition.swagger.json
- certified-connectors/AXtension Content Gate/apiProperties.json
- certified-connectors/AXtension Content Gate/readme.md
> Added AXtension connector artifacts

- certified-connectors/PowerToolsLITE/apiDefinition.swagger.json
- certified-connectors/PowerToolsLITE/apiProperties.json
- certified-connectors/PowerToolsLITE/readme.md
> Add PowerToolsLITE connector artifacts

- custom-connectors/Facebook/apiProperties.json
**Reference:** https://developers.facebook.com/docs/graph-api/reference
> Updating Scopes as per new API documentation

- certified-connectors/BoomappConnect/Readme.md
- certified-connectors/BoomappConnect/apiDefinition.swagger.json
- certified-connectors/BoomappConnect/apiProperties.json
Iniitial submission of boomapp connect
---
> Initial Submission

- certified-connectors/MeetingRoomMap/apiDefinition.swagger.json
- certified-connectors/MeetingRoomMap/apiProperties.json
- certified-connectors/MeetingRoomMap/readme.md
> Adding MeetingRoomMap connector

- certified-connectors/Notiivy/README.md
- certified-connectors/Notiivy/apiDefinition.swagger.json
- certified-connectors/Notiivy/apiProperties.json
> Added Nottivy connector files

- certified-connectors/CDK Drive Service Vehicles/Readme.md
- certified-connectors/CDK Drive Service Vehicles/apiDefinition.swagger.json
- certified-connectors/CDK Drive Service Vehicles/apiProperties.json
> Initial commit for the CDK Drive Service Vehicle connector

- certified-connectors/Africa's Talking SMS/README.md
- certified-connectors/Africa's Talking SMS/apiDefinition.swagger.json
- certified-connectors/Africa's Talking SMS/apiProperties.json
> Add Africa's Talking SMS connector

- custom-connectors/Infobip/README.md
- custom-connectors/Infobip/apiDefinition.swagger.json
- custom-connectors/Infobip/apiProperties.json
> Add Infobip connector

- certified-connectors/Africa's Talking Payments/README.md
- certified-connectors/Africa's Talking Payments/apiDefinition.swagger.json
- certified-connectors/Africa's Talking Payments/apiProperties.json
Add Africa's Talking Payments Connector.
> Add payments connector

- certified-connectors/Way We Do/apiDefinition.swagger.json
- certified-connectors/Way We Do/apiProperties.json
- certified-connectors/Way We Do/readme.md
Rename of connector
Additional trigger
Minor and non-breaking updates to properties in schema
---
> Way We Do connector updates

- certified-connectors/Gravity Forms by reenhanced/apiDefinition.swagger.json
- certified-connectors/Gravity Forms by reenhanced/apiProperties.json
- certified-connectors/Gravity Forms by reenhanced/readme.md
Certified and tested connector for Gravity Forms by reenhanced
> Gravty Forms by reenhanced initial release

- certified-connectors/MotaWordTranslations/apiDefinition.swagger.json
- certified-connectors/MotaWordTranslations/apiProperties.json
- certified-connectors/MotaWordTranslations/readme.md
Here we are launching our MotaWord Translations connector! All seems fine on our side, let us know if you have any feedback.
---
> Initial launch of MotaWord Translations connector

- certified-connectors/GetMyInvoices/apiDefinition.swagger.json
- certified-connectors/GetMyInvoices/apiProperties.json
- certified-connectors/GetMyInvoices/readme.md
> Add GetMyInvoices Connector

- certified-connectors/Cloudmersive Video and Media/Readme.md
- certified-connectors/Cloudmersive Video and Media/apiDefinition.swagger.json
- certified-connectors/Cloudmersive Video and Media/apiProperties.json
---
- [ X ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ X ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> Added Cloudmersive Video and Media Connector

- certified-connectors/CDK Drive Customers/Readme.md
- certified-connectors/CDK Drive Customers/apiDefinition.swagger.json
- certified-connectors/CDK Drive Customers/apiProperties.json
> Initial commit for CDK Customer API connector

- certified-connectors/Data8/apiDefinition.swagger.json
- certified-connectors/Data8/apiProperties.json
- certified-connectors/Data8/readme.md
> Updated Data8 connector

- certified-connectors/Peltarion/README.md
> Updated readme

- certified-connectors/Nitro/apiDefinition.swagger.json
- certified-connectors/Nitro/apiProperties.json
- certified-connectors/Nitro/readme.md
> Add Nitro connector

- certified-connectors/Rencore Governance/apiDefinition.swagger.json
- certified-connectors/Rencore Governance/apiProperties.json
> Updates Rencore Governance connector

- certified-connectors/AvePoint Cloud Governance/Readme.md
- certified-connectors/AvePoint Cloud Governance/apiDefinition.swagger.json
- certified-connectors/AvePoint Cloud Governance/apiProperties.json
---
- [checked ] `apiDefinition.swagger.json` is validated using `paconn validate` command. 
- [checked  ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.  done
> Add AvePoint Cloud Governance connector

- certified-connectors/WorkSpan/apiDefinition.swagger.json
- certified-connectors/WorkSpan/apiProperties.json
New Action: Update External Id
New Action: Get External Id
New Actions: New Bulkload Action for ALL objects (leads/ accounts)
New Action: Get Status
New Action: Object Audit
New Trigger: Submit to Partner Center
Usability Enhancements:
Enabled selection of integration by dynamically fetching
list of integrations. No need to add integration_id
---
> WorkSpan connector new trigger and actions

- certified-connectors/Scrive eSign/apiDefinition.swagger.json
> Update Scrive eSign connector

- certified-connectors/GetAccept/apiDefinition.swagger.json
- certified-connectors/GetAccept/apiProperties.json
- certified-connectors/GetAccept/readme.md
> Add GetAccept connector

- certified-connectors/AXtension Content Gate/apiDefinition.swagger.json
- certified-connectors/RecordedFuture/apiDefinition.swagger.json
'x-ms-editor-options' was not fully supported, the right way is to use 'x-ms-enum-values' extension
> Replace deprecated 'x-ms-editor-options' with 'x-ms-enum-values'

- certified-connectors/tyntec-SMS/apiDefinition.swagger.json
> Updated Responses

- certified-connectors/Connective eSignatures/Readme.md
- certified-connectors/Connective eSignatures/apiDefinition.swagger.json
- certified-connectors/Connective eSignatures/apiProperties.json
This is our submission for the Connective eSignatures Connector.
> add the Connective eSignatures Connector

- certified-connectors/AzureAD/apiDefinition.swagger.json
---
- [ X] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ X] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> Added Extension Attributes in User Update Request

- certified-connectors/Dokobit Portal/apiDefinition.swagger.json
- certified-connectors/Dokobit Portal/apiProperties.json
- certified-connectors/Dokobit Portal/readme.md
> Dokobit Portal initial submission

- certified-connectors/PDF Blocks/apiDefinition.swagger.json
> PDF Blocks v1.2.0

- certified-connectors/FORCAM FORCE Bridge/apiDefinition.swagger.json
- Add new trigger ProcessDataRuleViolated
- Cleaned up some definitions
---
> Add new Trigger "ProcessDataRuleViolated"

- certified-connectors/PowerToolsPRO/apiDefinition.swagger.json
- certified-connectors/PowerToolsPRO/apiProperties.json
- certified-connectors/PowerToolsPRO/readme.md
> Add Apptigent PowerToolsPRO connector

- certified-connectors/Connect2All/apiDefinition.swagger.json
- certified-connectors/Connect2All/apiProperties.json
> October Update of Connector

- certified-connectors/Cloudmersive Currency/Readme.md
- certified-connectors/Cloudmersive Currency/apiDefinition.swagger.json
- certified-connectors/Cloudmersive Currency/apiProperties.json
- certified-connectors/Cloudmersive Video and Media/Readme.md
---
- [ X ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ X ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> Added Cloudmersive Currency Connector

- certified-connectors/Ubiqod by Skiply/apiDefinition.swagger.json
> Update category from IOT to Internet of Things

- certified-connectors/Peltarion/README.md
- certified-connectors/Peltarion/apiDefinition.swagger.json
> Updated connector title

- certified-connectors/AtBot Admin/README.md
- certified-connectors/AtBot Admin/apiDefinition.swagger.json
- certified-connectors/AtBot Admin/apiProperties.json
Initial submission for AtBot Admin connector.
---
- [X ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ X] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> AtBot Admin Connector

- certified-connectors/Peltarion/README.md
- certified-connectors/Peltarion/apiDefinition.swagger.json
> Updated description

- certified-connectors/Huddle US/apiDefinition.swagger.json
- certified-connectors/Huddle US/apiProperties.json
- certified-connectors/Huddle US/readme.md
> Huddle US (New fork version :-) )

- custom-connectors/AzureAdIp/apiProperties.json
> [Fix] fix API properties

- certified-connectors/CognitiveServicesTextAnalytics/apiDefinition.swagger.json
A small fix to remove erroneous error responses in the expected responses description
> remove default response for errors

- certified-connectors/HYAS Insight/apiDefinition.swagger.json
> API updates to reflect latest HYAS Insight release.

- certified-connectors/COSMO Bot/Readme.md
- certified-connectors/COSMO Bot/apiDefinition.swagger.json
- certified-connectors/COSMO Bot/apiProperties.json
> Initial commit for COSMO Bot certification

- certified-connectors/HYAS Insight/apiDefinition.swagger.json
> Update to reflect latest HYAS Insight APIs

- certified-connectors/Expensya/apiDefinition.swagger.json
- certified-connectors/Expensya/apiProperties.json
- certified-connectors/Expensya/readme.md
> Expensya Connector PR

- certified-connectors/Dokobit Portal/apiDefinition.swagger.json
> Dokobit Portal - webhooks & small notation fixes

- custom-connectors/AzureAdIp/apiDefinition.swagger.json
> Aadip update userids visibility

- certified-connectors/CRMBot/apiDefinition.swagger.json
- certified-connectors/CRMBot/apiProperties.json
- certified-connectors/CRMBot/readme.md
> Add CRMBot connector

- certified-connectors/sms77io/apiDefinition.swagger.json
- certified-connectors/sms77io/apiProperties.json
- certified-connectors/sms77io/readme.md
> Add connector sms77io

- certified-connectors/VirusTotal/apiDefinition.swagger.json
> rename operation id to match deployed version

- certified-connectors/Plumsail SP/apiDefinition.swagger.json
Added hidden operation FlowV1SharePointFlowSchemaGetRoleTypesPost
> FlowV1SharePointFlowSchemaGetRoleTypesPost

- certified-connectors/Yeeflow/apiDefinition.swagger.json
- certified-connectors/Yeeflow/apiProperties.json
- certified-connectors/Yeeflow/readme.md
> Submit for certification

- certified-connectors/Plumsail HelpDesk/apiDefinition.swagger.json
- certified-connectors/Plumsail HelpDesk/apiProperties.json
- certified-connectors/Plumsail HelpDesk/readme.md
> Update Plumsail HelpDesk connector

- certified-connectors/Poka/Readme.md
> Update Poka Readme.md

- certified-connectors/Kanbanize/Readme.md
- certified-connectors/Kanbanize/apiDefinition.swagger.json
- certified-connectors/Kanbanize/apiProperties.json
> Kanbanize - Initial Connector Revision

- certified-connectors/envoy/apiDefinition.swagger.json
- certified-connectors/envoy/apiProperties.json
> update api def and api properties files

- certified-connectors/Bitvore/README.md
- certified-connectors/Bitvore/apiDefinition.swagger.json
- certified-connectors/Bitvore/apiProperties.json
> Submit Bitvore Cellenus Entity API connector

- certified-connectors/Yeeflow/apiDefinition.swagger.json
> Change type of FieldID to string, remove columnType paramter from hooks

- certified-connectors/sms77io/apiDefinition.swagger.json
---
- [ x] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [x ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> sms77io: updated swagger definition

- certified-connectors/Enadoc/apiDefinition.swagger.json
- certified-connectors/Enadoc/apiProperties.json
- certified-connectors/Enadoc/readme.md
> Added Enadoc connector artifacts

- tools/paconn-cli/paconn/__init__.py
- tools/paconn-cli/setup.py
> Upgrade to version 0.15

- certified-connectors/Public360/Readme.md
- certified-connectors/Public360/apiDefinition.swagger.json
- certified-connectors/Public360/apiProperties.json
> Public 360 commit

- certified-connectors/Docurain/apiDefinition.swagger.json
> remove 422 and 599 response code

- certified-connectors/Cloudmersive Barcode/apiDefinition.swagger.json
- certified-connectors/Cloudmersive Barcode/apiProperties.json
---
- [ X ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ X ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> Updated Cloudmersive Barcode Connector

- certified-connectors/envoy/apiDefinition.swagger.json
> fix user-data array in POST Invite

- certified-connectors/Cloud BOT/Readme.md
- certified-connectors/Cloud BOT/apiDefinition.swagger.json
- certified-connectors/Cloud BOT/apiProperties.json
> Cloud BOT Connector

- certified-connectors/Encodian/Readme.md
- certified-connectors/Encodian/apiDefinition.swagger.json
> Encodian Nov 20 Release - Updated

- certified-connectors/Transform2All/apiDefinition.swagger.json
- certified-connectors/Transform2All/apiProperties.json
- certified-connectors/Transform2All/readme.md
> Transform2All - Initial Version

- certified-connectors/Ephesoft/apiDefinition.swagger.json
- certified-connectors/Ephesoft/apiProperties.json
- certified-connectors/Ephesoft/readme.md
Adding the Ephesoft Semantik For Invoices connector.  The connector is a dynamic webhook trigger and has no actions.
* Manual testing
* paconn validated successfully (no errors or warnings)
> Add Ephesoft Semantik For Invoices Connector

- certified-connectors/Evocom/Readme.md
- certified-connectors/Evocom/apiDefinition.swagger.json
- certified-connectors/Evocom/apiProperties.json
- certified-connectors/Kanbanize/apiProperties.json
SAS Intelligent Decisioning on SAS Viya combines business rules management, decision processing, real-time event detection, decision governance, and powerful SAS advanced analytics to automate and manage decisions across the enterprise. SAS Intelligent Decisioning helps expedite the operationalization of analytical models, including both SAS models and those developed with open source frameworks. It supports the decisioning process in credit services, fraud prevention, manufacturing, personalized marketing, and many other use cases.
> Added SAS Decisioning connector

- certified-connectors/Cloud BOT/apiDefinition.swagger.json
> Fixed summary values.

- certified-connectors/Encodian/apiDefinition.swagger.json
> Encodian Nov 20 Release #2

- certified-connectors/cioplenu/README.md
- certified-connectors/cioplenu/apiDefinition.swagger.json
- certified-connectors/cioplenu/apiProperties.json
Initial submission for certification of the cioplenu connector
> initial cioplenu connector

- certified-connectors/CDK Drive Service Vehicles/Readme.md
> Minor change in readme.md to upload an image

- certified-connectors/Industrial App Store/README.MD
- certified-connectors/Industrial App Store/apiDefinition.swagger.json
- certified-connectors/Industrial App Store/apiProperties.json
> Industrialappstore add

- certified-connectors/Ubiqod by Skiply/Readme.md
- certified-connectors/Ubiqod by Skiply/apiDefinition.swagger.json
New fields was added to the platform, and need to be available for use by the connector.
Field description was updated to include Qods (previously, only buttons was described).
Website and privacy policy was moved to a dedicated ressource.
Readme was modified to reflect changes.
---
> New fields, updated descriptions and minor changes

- certified-connectors/PDF4me Connect/apiDefinition.swagger.json
- certified-connectors/PDF4me Connect/apiProperties.json
- certified-connectors/PDF4me Connect/readme.md
> Pull Request from Patch 2 to dev

- certified-connectors/PowerToolsPRO/apiDefinition.swagger.json
> PowerTools PRO v1.3

- certified-connectors/E-goi/apiDefinition.swagger.json
- certified-connectors/E-goi/apiProperties.json
- certified-connectors/E-goi/readme.md
> Egoi connector

- certified-connectors/Expensya/apiProperties.json
> Expensya Rebranding: Update iconBrandColor

- certified-connectors/Bitvore/apiDefinition.swagger.json
> Bug fixes and updates to description

- certified-connectors/TPCPortal/apiDefinition.swagger.json
> TPC Portal - Updated Operation Status

- certified-connectors/RiskIQDigitalFootprint/README.md
- certified-connectors/RiskIQDigitalFootprint/apiDefinition.swagger.json
- certified-connectors/RiskIQDigitalFootprint/apiProperties.json
> RiskIQ Digital Footprint initial commit for certification

- certified-connectors/HuddoBoards/README.md
- certified-connectors/HuddoBoards/apiDefinition.swagger.json
- certified-connectors/HuddoBoards/apiProperties.json
Hi there,
Below is our proposal for the connector for Huddo Boards, we have completed all of the prerequisite tasks and have been contacted by Doug from Artech Consulting.
Hopefully this is sufficient, we will be more than happy to make any required changes.
Regards,
---
> Add Huddo Boards Connector

- certified-connectors/Lettria GDPR Compliance/apiDefinition.swagger.json
- certified-connectors/Lettria GDPR Compliance/apiProperties.json
- certified-connectors/Lettria GDPR Compliance/intro.md
- certified-connectors/Lettria GDPR Compliance/readme.md
> Added Lettria GDPR Compliance connector

- certified-connectors/Formstack Documents/apiProperties.json
- certified-connectors/Formstack Forms/README.md
- certified-connectors/Formstack Forms/apiDefinition.swagger.json
- certified-connectors/Formstack Forms/apiProperties.json
> Formstack Forms v1

- certified-connectors/ReversingLabs Intelligence/apiDefinition.swagger.json
> Add dynamic analysis APIs, user-agent, bulk-post models 

- certified-connectors/ReversingLabs Intelligence/apiDefinition.swagger.json
> Fix - param name

- certified-connectors/Pilot Things/apiDefinition.swagger.json
- certified-connectors/Pilot Things/apiProperties.json
- certified-connectors/Pilot Things/readme.md
> Add Pilot Things connector

- certified-connectors/ShowcaseWorkshop/README.md
- certified-connectors/ShowcaseWorkshop/apiDefinition.swagger.json
- certified-connectors/ShowcaseWorkshop/apiProperties.json
> New connector for Showcase Workshop

- custom-connectors/AzureAdIp/apiProperties.json
The changes allow the connector to use first party app
---
> [Fix] Change the application to first party application

- tools/paconn-cli/README.md
> Added a note for service principal authentication

- certified-connectors/PDF4me Connect/apiDefinition.swagger.json
> Added Mail Merge actions

- certified-connectors/TractionGuest/apiDefinition.swagger.json
- certified-connectors/TractionGuest/apiProperties.json
---
- [  ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ ✔️  ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> Updated copy to be more legible and clear.

- certified-connectors/Asite/Readme.md
- certified-connectors/Asite/apiDefinition.swagger.json
- certified-connectors/Asite/apiProperties.json
> Add new Asite connector

- certified-connectors/AzureAD/apiDefinition.swagger.json
- certified-connectors/AzureAD/apiProperties.json
Added custom properties to update user API.
> Added Custom Properties to Update User and also added MoveProperties

- certified-connectors/Blackbaud Raiser's Edge NXT/apiDefinition.swagger.json
> fixed invalid type; added linked gifts, gift code

- certified-connectors/Scrive eSign/apiDefinition.swagger.json
- certified-connectors/Scrive eSign/apiProperties.json
- certified-connectors/Scrive eSign/readme.md
> Update with new actions

- certified-connectors/Nitro/apiDefinition.swagger.json
> Update Nitro connector

- certified-connectors/LassoX/apiDefinition.swagger.json
- certified-connectors/LassoX/apiProperties.json
- certified-connectors/LassoX/readme.md
This PR submits the connector for Lasso X to be certified.
> Add Lasso X as a certified connector

- certified-connectors/Survey123/apiDefinition.swagger.json
- certified-connectors/Survey123/apiProperties.json
- certified-connectors/Survey123/readme.md
> add Survey123 connector

- certified-connectors/ReversingLabs Intelligence/apiDefinition.swagger.json
> User agent, json as default response

- certified-connectors/Aletheia/apiDefinition.swagger.json
- certified-connectors/Aletheia/apiProperties.json
- certified-connectors/Aletheia/readme.md
> Addition of Aletheia connector

- certified-connectors/HrFlow/README.md
- certified-connectors/HrFlow/apiDefinition.swagger.json
- certified-connectors/HrFlow/apiProperties.json
> Add HrFlow.ai custom connector

- certified-connectors/RiskIQPassiveTotal/apiDefinition.swagger.json
- certified-connectors/RiskIQPassiveTotal/apiProperties.json
- certified-connectors/RiskIQPassiveTotal/readme.md
> RiskIQ PassiveTotal Connector

- certified-connectors/Aletheia/apiDefinition.swagger.json
---
- [ x] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ x] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> Aletheia bug fixes and property type match corrections

- certified-connectors/StaffCircle/apiDefinition.swagger.json
- certified-connectors/StaffCircle/apiProperties.json
- certified-connectors/StaffCircle/readme.md
> StaffCircle Connector

- certified-connectors/RiskIQPassiveTotal/apiDefinition.swagger.json
- certified-connectors/RiskIQPassiveTotal/apiProperties.json
- certified-connectors/RiskIQPassiveTotal/readme.md
> Field description modified for RiskIQ PassiveTotal connector

- .github/workflows/dev-to-master.yml
Automatically sync dev to master
> Auto Sync Dev to Master

- certified-connectors/Plumsail Documents/apiDefinition.swagger.json
- certified-connectors/Plumsail SP/apiDefinition.swagger.json
* Add a new trigger for Plumsail Documents
* Add an action GetPdfProtectionInfo
* Add an action CompressPdf
* Minor changes in Actions/Document connectors
> 210330 plumsail update

- certified-connectors/Flotiq/apiDefinition.swagger.json
Please accept this change as the next step for providing compatibility with both Logic apps and Flow.
> additional compatibility for logic apps and flow

- certified-connectors/airSlate/Readme.md
- certified-connectors/airSlate/apiDefinition.swagger.json
- certified-connectors/airSlate/apiProperties.json
> airSlate Connector Initial Commit

- certified-connectors/DocuSign/apiDefinition.swagger.json
- certified-connectors/DocuSign/apiProperties.json
- certified-connectors/DocuSign/script.csx
> Made changes for open-sourcing DocuSign connector

- .github/CODEOWNERS
This reverts commit 9ff846b12840991c4930b690bb90fb67ddebfe69.
> Revert "Code owner update (#768)"

- custom-connectors/ServiceNow/Readme.md
Picked the wrong path for images during merge
---
> Updated readme with current images path

- certified-connectors/SignNow/apiDefinition.swagger.json
- certified-connectors/SignNow/apiProperties.json
> New authorization endpoints, required parameters and action changes.

- certified-connectors/Captisa Forms/apiDefinition.swagger.json
- certified-connectors/Captisa Forms/apiProperties.json
- certified-connectors/Captisa Forms/readme.md
> Captisa Forms

- certified-connectors/Encodian/apiDefinition.swagger.json
> Encodian March 21 Release

- certified-connectors/Aletheia/apiDefinition.swagger.json
- certified-connectors/Aletheia/readme.md
- certified-connectors/Captisa Forms/apiDefinition.swagger.json
- certified-connectors/Captisa Forms/apiProperties.json
- certified-connectors/Captisa Forms/readme.md
- certified-connectors/Encodian/apiDefinition.swagger.json
- certified-connectors/LatinShare Documents/apiDefinition.swagger.json
- certified-connectors/LatinShare Documents/apiProperties.json
- certified-connectors/LatinShare Documents/readme.md
- certified-connectors/LatinShare SHP Management/apiDefinition.swagger.json
- certified-connectors/LatinShare SHP Management/apiProperties.json
- certified-connectors/LatinShare SHP Management/readme.md
- certified-connectors/LatinShare SHP Permissions/apiDefinition.swagger.json
- certified-connectors/LatinShare SHP Permissions/apiProperties.json
- certified-connectors/LatinShare SHP Permissions/readme.md
- certified-connectors/Mavim iMprove/apiDefinition.swagger.json
- certified-connectors/Mavim iMprove/apiProperties.json
- certified-connectors/SignNow/apiDefinition.swagger.json
- certified-connectors/SignNow/apiProperties.json
- custom-connectors/ServiceNow/Readme.md
Sync changes from dev to master
---
> Updated readme with current images path (#767)

- certified-connectors/RAPID Platform/apiDefinition.swagger.json
- certified-connectors/RAPID Platform/apiProperties.json
- certified-connectors/RAPID Platform/readme.md
Pull Request as part of connector submission process for RAPID Platform
---
- [ X ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ X ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> Rapidplatform connector submission

- certified-connectors/DocJuris/README.md
- certified-connectors/DocJuris/apiDefinition.swagger.json
- certified-connectors/DocJuris/apiProperties.json
Submission of DocJuris connector.
---
- [X ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [X ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> Initial DocJuris submission

- certified-connectors/dox42/README.md
- certified-connectors/dox42/apiDefinition.swagger.json
- certified-connectors/dox42/apiProperties.json
> dox42 Custom Connector

- custom-connectors/Elfsquad Data/README.md
- custom-connectors/Elfsquad Data/apiDefinition.swagger.json
- custom-connectors/Elfsquad Data/apiProperties.json
---
- [X ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ X] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.
> Added Elfsquad Data connector

- custom-connectors/Datelist/README.md
- custom-connectors/Datelist/apiDefinition.swagger.json
- custom-connectors/Datelist/apiProperties.json
Microsoft flow connector for https://datelist.io 
Datelist is an online booking system platform that allows customers taking meetings online. 
- New booking: Triggers when someone books a meeting in the Datelist platform 
- Get calendars: List all available calendars in Datelist.io 
I've tried to make our organization name as the Stack owner (datelist.io), but I get the following error: 
> The request content was invalid and could not be deserialized: 'Could not find member 'stackOwner' on object of type 'ApiPropertiesDefinition'. Path 'properties.stackOwner', line 1, position 384.'. 
So, I've put my personal name here "Clarembeau Alexis", do you know what are the accepted values in that field? 
> Add Datelist connector 

- certified-connectors/Peltarion/README.md
> Updated instructions

- certified-connectors/SignNow/apiDefinition.swagger.json
> Advanced Document Invite operation added & bug fixes

- certified-connectors/Projectplace/apiDefinition.swagger.json
- certified-connectors/Projectplace/apiProperties.json
- Change ID's to int64
- Enable moving card by ID
- Changing the icon colour for updating the icon
> Projectplace connector

- certified-connectors/SignNow/apiDefinition.swagger.json
- certified-connectors/SignNow/apiProperties.json
> Add Enum Support to Document Fields. Update Authorization Url

- .github/pull_request_template.md
- independent-publisher-connectors/OpenWeather/apiDefinition.swagger.json
- independent-publisher-connectors/OpenWeather/apiProperties.json
- independent-publisher-connectors/readme.md
> ip connector entry

- .github/pull_request_template.md
> Fixed a typo

- certified-connectors/Assently E-Sign/Readme.md
- certified-connectors/Assently E-Sign/apiDefinition.swagger.json
- certified-connectors/Assently E-Sign/apiProperties.json
> Adds Assently E-Sign custom connector for certification

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/New_connector_request.md
> Added template

- certified-connectors/DeskDirector/README.md
- certified-connectors/DeskDirector/apiDefinition.swagger.json
- certified-connectors/DeskDirector/apiProperties.json
> Initial commit of DeskDirector connector

- certified-connectors/Yeeflow/apiDefinition.swagger.json
- certified-connectors/Yeeflow/apiProperties.json
---
Changed version No. and iconBrandColor.
> v2.0 change iconBrandColor

- README.md
@mamurshe, I made the changes as discussed.
---
> Update README.md again 

- certified-connectors/HARNESS PDFx/README.md
- certified-connectors/HARNESS PDFx/apiDefinition.swagger.json
- certified-connectors/HARNESS PDFx/apiProperties.json
> Added files for certification

- certified-connectors/HARNESS PDFx/apiDefinition.swagger.json
> Updated connector name and support email

- certified-connectors/Plumsail Documents/apiDefinition.swagger.json
- Fixed trigger remove action
- Added an additional argument password for two actions
- Small naming improvements
> Fix trigger

- certified-connectors/secplugs/apiDefinition.swagger.json
removed json_report element from response
---
> removed json_report element from response

- .github/pull_request_template.md
> Adding a bullet point for descriptions to the PR template

- certified-connectors/WorkPoint/apiDefinition.swagger.json
> Update WorkPoint Connector to version 1.1

- tools/paconn-cli/paconn/apimanager/powerappsrp.py
---
Adds a header extension to rp connector tasks for source telemetry.
> Add User Agent Header to RP Requests

- certified-connectors/Almabase/apiDefinition.swagger.json
- certified-connectors/Almabase/apiProperties.json
- certified-connectors/Almabase/readme.md
> Almabase: Ready for Certification

- certified-connectors/Charles Universe/README.md
- certified-connectors/Charles Universe/apiDefinition.swagger.json
- certified-connectors/Charles Universe/apiProperties.json
Signed-off-by: Robert Jefe Lindstaedt <robert.lindstaedt@gmail.com>
---
Note: I believe the host injection cannot be tested before deployment. At least we have found no way around it. Hence we are testing against cucstom connector
> feat(Charles): add initial implementation

- certified-connectors/Gratavid/README.md
- certified-connectors/Gratavid/apiDefinition.swagger.json
- certified-connectors/Gratavid/apiProperties.json
> Submit Gratavid certified connector

- certified-connectors/Integration Toolbox/README.md
- certified-connectors/Integration Toolbox/apiDefinition.swagger.json
- certified-connectors/Integration Toolbox/apiProperties.json
> Integration Toolbox

- certified-connectors/document-ai-konfuzio/README.md
- certified-connectors/document-ai-konfuzio/apiDefinition.swagger.json
- certified-connectors/document-ai-konfuzio/apiProperties.json
> Add Document AI Konfuzio as Certified Connector

- certified-connectors/TxtSync/apiDefinition.swagger.json
- certified-connectors/TxtSync/apiProperties.json
- certified-connectors/TxtSync/readme.md
> TxtSync SMS Connector - ready for certification

- tools/paconn-cli/paconn/apimanager/powerappsrp.py
Change the powerapps-rp header in response to RP update.
> Update Header to Reflect New RP Changes

- certified-connectors/VirusTotal/apiDefinition.swagger.json
- certified-connectors/VirusTotal/apiProperties.json
> Update virus total connector handle breaking change

- certified-connectors/HARNESS PDFx/apiDefinition.swagger.json
> Made Harness lowercase in title

- certified-connectors/WenDocs Linker/README.md
- certified-connectors/WenDocs Linker/apiDefinition.swagger.json
- certified-connectors/WenDocs Linker/apiProperties.json
> create WenDocs Linker

- certified-connectors/Connect2All/apiDefinition.swagger.json
> Added extra update method to connector

- independent-publisher-connectors/readme.md
> Added screenshot requirement

- independent-publisher-connectors/JiraSearch/apiDefinition.swagger.json
- independent-publisher-connectors/JiraSearch/apiProperties.json
- independent-publisher-connectors/JiraSearch/readme.md
---
- [ x] I attest that the connector works and I verified by deploying and testing all the operations.
- [ x] I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`.
> Jira Search independent connector

- independent-publisher-connectors/Airtable/apiDefinition.swagger.json
- independent-publisher-connectors/Airtable/apiProperities.json
- independent-publisher-connectors/Airtable/apiProperties.json
- independent-publisher-connectors/Airtable/readme.md
> IP Connector Airtable

- independent-publisher-connectors/Atlassian Jira/README.md
- independent-publisher-connectors/Atlassian Jira/apiDefinition.swagger.json
- independent-publisher-connectors/Atlassian Jira/apiProperties.json
Extends the existing Jira connector. Added apiDefinition, apiProperties and Readme
---
> [Independent-Publisher] v1 Jira Connector

- independent-publisher-connectors/Care Quaility Comission For England/CQC-Connector.swagger.json
- independent-publisher-connectors/Care Quaility Comission For England/README.md
- independent-publisher-connectors/Care Quaility Comission For England/apiProperties.json
> Care Quality Commission for England  I.P.C. 

- certified-connectors/Almabase/apiDefinition.swagger.json
- certified-connectors/Almabase/apiProperties.json
> Almabase: Fixed the pagination issue with Gifts & Records action.

- independent-publisher-connectors/readme.md
> callout Independent Publisher connectors are premium

- .github/pull_request_template.md
> Updated PR template per retro & fixed spelling mistake

- tools/paconn-cli/paconn/__init__.py
- tools/paconn-cli/setup.py
> Versioning bump

- README.md
Fixed the directory name as independent-publisher-connectors instead of custom-connector
> Fixed the directory name

- certified-connectors/Egnyte/README.md
- certified-connectors/Egnyte/apiDefinition.swagger.json
- certified-connectors/Egnyte/apiProperties.json
> New Connector: Egnyte

- certified-connectors/PowerToolsPRO/apiDefinition.swagger.json
- certified-connectors/PowerToolsPRO/readme.md
---
- [ x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.
If you are an Independent Publisher, you must also attest to the following to ensure a …
> PowerTools PRO v1.4.0

- certified-connectors/secplugs/apiDefinition.swagger.json
- certified-connectors/secplugs/apiProperties.json
- certified-connectors/secplugs/readme.md
> Renamed secplug to seplugs

- certified-connectors/BoomappConnect/apiProperties.json
Original publisher is not longer trading as a business. Updating publisher to the owner of the underlying messaging platform and removing reference to closed business. 
---
- [ x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an …
> Update publisher information

- certified-connectors/sms77io/apiDefinition.swagger.json
- certified-connectors/sms77io/readme.md
---
- [ x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.
If you are an Independent Publisher, you must also attest to the following to ensure a …
> update custom connector sms77io

- certified-connectors/Elfsquad Data/apiDefinition.swagger.json
Added a orderby paramter to the get_entities operation
> Updated Elfsquad Data Connector

- certified-connectors/RAPID Platform/apiProperties.json
- certified-connectors/RAPID Platform/readme.md
Updated apiProperties.json to direct to the production environment instead of test
Updated minor errors in readme.md
---
> Rapid v1.4

- independent-publisher-connectors/HubSpot Marketing/README.md
> Fixed wrong header

- certified-connectors/Polaris PSA/README.md
- certified-connectors/Polaris PSA/apiDefinition.swagger.json
- certified-connectors/Polaris PSA/apiProperties.json
> Polaris PSA certified connector

- independent-publisher-connectors/readme.md
> Fixed broken links and removed Etsy from top requests.

- certified-connectors/IA-Connect Dynamic Code/README.md
- certified-connectors/IA-Connect Dynamic Code/apiDefinition.swagger.json
- certified-connectors/IA-Connect Dynamic Code/apiProperties.json
---
- [N/A] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [N/A] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [N/A] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [N/A] If the …
> Uploading IA-Connect Dynamic Code connector for certification

- custom-connectors/ServiceNow/apiDefinition.swagger.json
Added a new action Get User. Please let me know if there is anything more I need to submit. 
---
> Added a new action Get User

- certified-connectors/Cloudmersive Security/Readme.md
- certified-connectors/Cloudmersive Security/apiDefinition.swagger.json
- certified-connectors/Cloudmersive Security/apiProperties.json
---
- [ X ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ X ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ X ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ X ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.
> Added Cloudmersive Security Connector

- certified-connectors/Almabase/apiDefinition.swagger.json
> August Updates for Almabase Connector

- certified-connectors/Cloudspark EXP Leave/README.md
- certified-connectors/Cloudspark EXP Leave/apiDefinition.swagger.json
- certified-connectors/Cloudspark EXP Leave/apiProperties.json
> Cloudspark EXP Leave

- independent-publisher-connectors/What3Words/apiDefinition.swagger.json
- independent-publisher-connectors/What3Words/apiProperties.json
- independent-publisher-connectors/What3Words/readme.md
> What3Words (Independent Publisher)

- certified-connectors/Sociabble/apiDefinition.swagger.json
- certified-connectors/Sociabble/apiProperties.json
- certified-connectors/Sociabble/readme.md
---
- [ X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.
If you are an Independent Publisher, you must also attest to the following to ensure a …
> New connector : Sociabble

- independent-publisher-connectors/Yelp/apiDefinition.swagger.json
- independent-publisher-connectors/Yelp/apiProperties.json
- independent-publisher-connectors/Yelp/readme.md
> Yelp (Independent Publisher)

- certified-connectors/AzureIoTCentral/README.md
- certified-connectors/AzureIoTCentral/apiDefinition.swagger.json
> Azure IoT Central V3 - release 20210827

- independent-publisher-connectors/Discord/apiDefinition.swagger.json
- independent-publisher-connectors/Discord/apiProperties.json
- independent-publisher-connectors/Discord/readme.md
> Discord (Independent Publisher)

- independent-publisher-connectors/Spotify/apiDefinition.swagger.json
- independent-publisher-connectors/Spotify/apiProperties.json
- independent-publisher-connectors/Spotify/readme.md
> Spotify (Independent Publisher)

- certified-connectors/HoneywellForge/README.md
- certified-connectors/HoneywellForge/apiDefinition.swagger.json
- certified-connectors/HoneywellForge/apiProperties.json
> adding connector HoneyWellForge

- independent-publisher-connectors/AccuWeather/apiDefinition.swagger.json
- independent-publisher-connectors/AccuWeather/apiProperties.json
- independent-publisher-connectors/AccuWeather/readme.md
> AccuWeather (Independent Connector)

- certified-connectors/Peltarion/README.md
- certified-connectors/Peltarion/apiDefinition.swagger.json
* Added text similarity compatibility (new path/operation).
* Updated docs e.g. reflecting new functionality.
* Fixed minor errors.
> Certified connector Peltarion version 1.1 updates.

- certified-connectors/ZohoSign/apiProperties.json
> brand color changes done for Zohosign.

- certified-connectors/Connective eSignatures/Readme.md
This PR only updates documentation links in Readme.md
> update links to the documentation site

- independent-publisher-connectors/JiraSearch/apiDefinition.swagger.json
- independent-publisher-connectors/JiraSearch/readme.md
> Jira Search (Independent Publisher)

- certified-connectors/AXtension Content Gate/apiDefinition.swagger.json
> AXtension Content Gate - Connector updates

- certified-connectors/Peltarion/README.md
Minor typo fix and readme extension.
> Certified connector Peltarion | Minor typo fix and readme extension.

- certified-connectors/Spinpanel/apiDefinition.swagger.json
- certified-connectors/Spinpanel/apiProperties.json
- certified-connectors/Spinpanel/readme.md
> Added Spinpanel and connector files to the certified connectors folder to prepare for certification

- certified-connectors/DocJuris/apiDefinition.swagger.json
---
- [ * ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ * ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ * ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ * ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ * ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.
If you are an Independent Publisher, you must also attest to the following to ensure a smooth …
> DocJuris Connector v3.1

- independent-publisher-connectors/New York Times/apiDefinition.swagger.json
- independent-publisher-connectors/New York Times/apiProperties.json
- independent-publisher-connectors/New York Times/readme.md
> New York Times (Independent Publisher)

- independent-publisher-connectors/The Weather Channel/apiDefinition.swagger.json
- independent-publisher-connectors/The Weather Channel/apiProperties.json
- independent-publisher-connectors/The Weather Channel/readme.md
> The Weather Channel (Independent Publisher)

- certified-connectors/Data8/apiDefinition.swagger.json
- certified-connectors/Data8/apiProperties.json
- certified-connectors/Data8/script.csx
---
- [ x ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ x ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ x ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ x ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ x ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.
If you are an Independent Publisher, you must also attest to the following to ensure a smooth …
> Updated and added script

- certified-connectors/Dynamics365FraudProtection/apiDefinition.swagger.json
- certified-connectors/Dynamics365FraudProtection/apiProperties.json
> Move hostUrl from connection parameter to operation parameter

- certified-connectors/RecordedFutureV2/apiDefinition.swagger.json
> Fix swagger issues discovered during preview testing

- templates/readme.md
Updated template text for readme.md
---
> Updated template text for readme.md

- independent-publisher-connectors/Coinbase/apiDefinition.swagger.json
- independent-publisher-connectors/Coinbase/apiProperties.json
- independent-publisher-connectors/Coinbase/readme.md
> Coinbase (Independent Publisher)

- certified-connectors/Ideanote/README.md
- certified-connectors/Ideanote/apiDefinition.swagger.json
- certified-connectors/Ideanote/apiProperties.json
> Ideanote (Certified Connector)

- certified-connectors/Adobe Creative Cloud Libraries/README.md
- certified-connectors/Adobe Creative Cloud Libraries/apiDefinition.swagger.json
- certified-connectors/Adobe Creative Cloud Libraries/apiProperties.json
> Adobe Creative Cloud Libraries (Certified Connector)

- certified-connectors/Eduframe/apiDefinition.swagger.json
> Update additional properties to be true by default

- certified-connectors/DataMotion/apiDefinition.swagger.json
> Updated 'Message request body' to be required

- certified-connectors/RecordedFutureV2/apiDefinition.swagger.json
> Fix additional errors discovered in preview testing

- certified-connectors/SurveyMonkey/apiDefinition.swagger.json
- certified-connectors/SurveyMonkey/apiProperties.json
- certified-connectors/SurveyMonkey/readme.md
- certified-connectors/SurveyMonkey/script.csx
> Open-source SurveyMonkey Connector

- certified-connectors/RescoCloud/apiDefinition.swagger.json
- certified-connectors/RescoCloud/apiProperties.json
> Add Generate Report

- certified-connectors/Jedox OData Hub/apiDefinition.swagger.json
- certified-connectors/Jedox OData Hub/apiProperties.json
- certified-connectors/Jedox OData Hub/readme.md
> Jedox OData Hub Connector

- certified-connectors/Dynamics365FraudProtection/apiDefinition.swagger.json
- certified-connectors/Dynamics365FraudProtection/apiProperties.json
> Move "hostUrl" to headers

- independent-publisher-connectors/AfterShip/apiDefinition.swagger.json
- independent-publisher-connectors/AfterShip/apiProperties.json
- independent-publisher-connectors/AfterShip/readme.md
> AfterShip (Independent Publisher)

- certified-connectors/Nodefusion Portal/Readme.md
- certified-connectors/Nodefusion Portal/apiDefinition.swagger.json
- certified-connectors/Nodefusion Portal/apiProperties.json
> New Nodefusion Portal certified connector submission 

- certified-connectors/InEight/apiDefinition.swagger.json
- certified-connectors/InEight/apiProperties.json
- certified-connectors/InEight/readme.md
> updated the files based on review from microsoft

- certified-connectors/Blackbaud Raiser's Edge NXT Constituents/apiDefinition.swagger.json
- certified-connectors/Blackbaud Raiser's Edge NXT Constituents/apiProperties.json
- certified-connectors/Blackbaud Raiser's Edge NXT Constituents/readme.md
- certified-connectors/Blackbaud Raiser's Edge NXT Constituents/script.csx
> adding RENXT Constituents connector

- certified-connectors/Blackbaud Raiser's Edge NXT Documents/apiDefinition.swagger.json
- certified-connectors/Blackbaud Raiser's Edge NXT Documents/apiProperties.json
- certified-connectors/Blackbaud Raiser's Edge NXT Documents/readme.md
> adding RENXT Documents connector

- certified-connectors/Blackbaud Raiser's Edge NXT Events/apiDefinition.swagger.json
- certified-connectors/Blackbaud Raiser's Edge NXT Events/apiProperties.json
- certified-connectors/Blackbaud Raiser's Edge NXT Events/readme.md
> adding RENXT Events connector

- certified-connectors/Blackbaud Raiser's Edge NXT Fundraising/apiDefinition.swagger.json
- certified-connectors/Blackbaud Raiser's Edge NXT Fundraising/apiProperties.json
- certified-connectors/Blackbaud Raiser's Edge NXT Fundraising/readme.md
- certified-connectors/Blackbaud Raiser's Edge NXT Fundraising/script.csx
> adding RENXT Fundraising connector

- certified-connectors/Blackbaud Raiser's Edge NXT Gifts/apiDefinition.swagger.json
- certified-connectors/Blackbaud Raiser's Edge NXT Gifts/apiProperties.json
- certified-connectors/Blackbaud Raiser's Edge NXT Gifts/readme.md
- certified-connectors/Blackbaud Raiser's Edge NXT Gifts/script.csx
> adding RENXT Gifts connector

- certified-connectors/Blackbaud Raiser's Edge NXT Interactions/apiDefinition.swagger.json
- certified-connectors/Blackbaud Raiser's Edge NXT Interactions/apiProperties.json
- certified-connectors/Blackbaud Raiser's Edge NXT Interactions/readme.md
- certified-connectors/Blackbaud Raiser's Edge NXT Interactions/script.csx
> adding RENXT Interactions connector

- certified-connectors/Blackbaud Raiser's Edge NXT Lists/apiDefinition.swagger.json
- certified-connectors/Blackbaud Raiser's Edge NXT Lists/apiProperties.json
- certified-connectors/Blackbaud Raiser's Edge NXT Lists/readme.md
> adding RENXT Lists connector

- certified-connectors/Blackbaud Raiser's Edge NXT Prospects/apiDefinition.swagger.json
- certified-connectors/Blackbaud Raiser's Edge NXT Prospects/apiProperties.json
- certified-connectors/Blackbaud Raiser's Edge NXT Prospects/readme.md
- certified-connectors/Blackbaud Raiser's Edge NXT Prospects/script.csx
> adding RENXT Prospects connector

- certified-connectors/Blackbaud SKY Add-ins/apiDefinition.swagger.json
- certified-connectors/Blackbaud SKY Add-ins/apiProperties.json
- certified-connectors/Blackbaud SKY Add-ins/readme.md
> adding Blackbaud SKY Add-ins connector

- certified-connectors/Connect2All/apiDefinition.swagger.json
- certified-connectors/Connect2All/apiProperties.json
> Added additional (bulk) actions

- certified-connectors/AXtension Content Gate/apiDefinition.swagger.json
> Added new actions/triggers

- independent-publisher-connectors/MailJet/apiDefinition.swagger.json
- independent-publisher-connectors/MailJet/apiProperties.json
- independent-publisher-connectors/MailJet/readme.md
> Mailjet (Independent Publisher)

- independent-publisher-connectors/Miro/Readme.md
- independent-publisher-connectors/Miro/apiDefinition.swagger.json
- independent-publisher-connectors/Miro/apiProperties.json
> Miro (Independent Publisher)

- independent-publisher-connectors/NASA Image and Video Library/Readme.md
- independent-publisher-connectors/NASA Image and Video Library/apiDefinition.swagger.json
- independent-publisher-connectors/NASA Image and Video Library/apiProperties.json
---
- [x ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding.
> NASA Image and Video Library (Independent Publisher)

- independent-publisher-connectors/NIST National Vulnerability Database/apiDefinition.swagger.json
- independent-publisher-connectors/NIST National Vulnerability Database/apiProperties.json
- independent-publisher-connectors/NIST National Vulnerability Database/readme.md
> NIST National Vulnerability Database (Independent Publisher)

- independent-publisher-connectors/Zippopotamus/Readme.md
- independent-publisher-connectors/Zippopotamus/apiDefinition.swagger.json
- independent-publisher-connectors/Zippopotamus/apiProperties.json
> Zippopotamus (Independent Publisher)

- independent-publisher-connectors/Companies House/apiDefinition.swagger.json
- independent-publisher-connectors/Companies House/apiProperties.json
- independent-publisher-connectors/Companies House/readme.md
- independent-publisher-connectors/Companies House/settings.json
> Companies house (independent publisher)

- certified-connectors/OpenExperience/apiDefinition.swagger.json
- certified-connectors/OpenExperience/apiProperties.json
- certified-connectors/OpenExperience/readme.md
> OpenExperience (Certified Connectors)

- certified-connectors/App Power Forms/apiDefinition.swagger.json
- certified-connectors/App Power Forms/apiProperties.json
- certified-connectors/App Power Forms/readme.md
> App Power Forms connector artifacts for certification

- certified-connectors/Lansweeper App For Sentinel/README.md
- certified-connectors/Lansweeper App For Sentinel/apiDefinition.swagger.json
- certified-connectors/Lansweeper App For Sentinel/apiProperties.json
> Added files for Lansweeper App For Sentinel Custom Connector

- certified-connectors/Connect2All/apiDefinition.swagger.json
Update descriptions of some methods.
Deprecated some methods (transformations).
Updated a method to be able to use custom lay-outs.
> Updated apiDefinition Connect2All

- certified-connectors/Lansweeper App For Sentinel/apiDefinition.swagger.json
> Update apiDefinition.swagger.json to fix the changes which found after deployed connector(Preview (United States)) testing

- certified-connectors/Exasol/README.md
- certified-connectors/Exasol/apiDefinition.swagger.json
- certified-connectors/Exasol/apiProperties.json
> Exasol (Non-Microsoft Publisher)

- certified-connectors/PKIsigning/apiDefinition.swagger.json
- certified-connectors/PKIsigning/apiProperties.json
- certified-connectors/PKIsigning/readme.md
> PKIsigning platform (certified connector)

- certified-connectors/IA-Connect Dynamic Code/apiDefinition.swagger.json
> Ia connect dynamiccode

- certified-connectors/YakChat/Readme.md
- certified-connectors/YakChat/apiDefinition.swagger.json
- certified-connectors/YakChat/apiProperties.json
> Added YakChat connector files

- certified-connectors/IA-Connect Session/apiDefinition.swagger.json
> Updated Swagger for IA-Connect 9.2 release

- certified-connectors/IA-Connect JML/README.md
- certified-connectors/IA-Connect JML/apiDefinition.swagger.json
- certified-connectors/IA-Connect JML/apiProperties.json
> Ia connect jml

- certified-connectors/DataMotion/README.md
- certified-connectors/DataMotion/apiDefinition.swagger.json
- certified-connectors/DataMotion/apiProperties.json
> Updated iconBrandColor

- certified-connectors/airSlate/apiDefinition.swagger.json
Schema updates: 
- add 'Create smart link' endpoint
- remove 'Send a Slate by email' endpoint
---
> Add 'Create smart link' endpoint

- certified-connectors/Airmeet/apiDefinition.swagger.json
- certified-connectors/Airmeet/apiProperties.json
- certified-connectors/Airmeet/script.csx
> Airmeet connector

- independent-publisher-connectors/MyHospitals by AIHW/Readme.md
- independent-publisher-connectors/MyHospitals by AIHW/apiDefinition.swagger.json
- independent-publisher-connectors/MyHospitals by AIHW/apiProperties.json
---
- [x ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.
If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing …
> AIHW My Hospitals (Independent Publisher)

- certified-connectors/CyberProof/apiDefinition.swagger.json
- certified-connectors/CyberProof/apiProperties.json
- certified-connectors/CyberProof/readme.md
> CyberProof connector

- certified-connectors/Mural/README.md
- certified-connectors/Mural/apiDefinition.swagger.json
- certified-connectors/Mural/apiProperties.json
> Open-source Mural Connector.

- certified-connectors/nunify/apiDefinition.swagger.json
- certified-connectors/nunify/apiProperties.json
- certified-connectors/nunify/readme.md
> nunify Connector

- certified-connectors/SurveyMonkey/apiDefinition.swagger.json
---
- [ Yes] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ Yes] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ Yes] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ Yes] I validated the swagger file, `apiDefinition.swagger.json`, by running …
> SurveyMonkey (Independent Publisher)

- certified-connectors/Airmeet/apiProperties.json
> [AIrmeet] stackOwner property added in the apiProperties

- certified-connectors/Iconfirm/apiDefinition.swagger.json
- certified-connectors/Iconfirm/apiProperties.json
- certified-connectors/Iconfirm/readme.md
> Iconfirm (Non-Microsoft Publisher)

- certified-connectors/AIForged/apiProperties.json
> AIForged: change order of customParameters in apiProperties.json

- custom-connectors/HtmlToText/apiDefinition.swagger.json
- custom-connectors/HtmlToText/apiProperties.json
- custom-connectors/HtmlToText/readme.md
- custom-connectors/HtmlToText/script.csx
> Initial version of HtmlToText custom connector

- independent-publisher-connectors/mondaycom/apiDefinition.swagger.json
- independent-publisher-connectors/mondaycom/apiProperties.json
- independent-publisher-connectors/mondaycom/readme.md
> mondaycom (Independent Publisher)

- certified-connectors/Aletheia/apiDefinition.swagger.json
---
- [X ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn …
> Updated property formats in Aletheia connector

- certified-connectors/RecordedFutureV2/apiDefinition.swagger.json
> Update RecordedFutureV2 connector with additional risk lists

- certified-connectors/sms77io/apiDefinition.swagger.json
---
- [x ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn …
> sms77io: add definition SmsResponse

- certified-connectors/Cyberday/Readme.md
- certified-connectors/Cyberday/apiDefinition.swagger.json
- certified-connectors/Cyberday/apiProperties.json
> Certify Cyberday connector

- certified-connectors/Power Textor/README.md
- certified-connectors/Power Textor/apiDefinition.swagger.json
- certified-connectors/Power Textor/apiProperties.json
> Power Textor

- certified-connectors/DocuSignDemo/script.csx
---
- [ x] I validated the swagger file, …
> FLOW-127: hotfix for connect configuration creation issues

- certified-connectors/ShortURL/apiProperties.json
> Apps365 ltd/short url

- independent-publisher-connectors/Finnish Railway Traffic/Readme.md
- independent-publisher-connectors/Finnish Railway Traffic/apiDefinition.swagger.json
- independent-publisher-connectors/Finnish Railway Traffic/apiProperties.json
> Finnish Railway Traffic (Independent Publisher)

- independent-publisher-connectors/Finnish BIS/Readme.md
- independent-publisher-connectors/Finnish BIS/apiDefinition.swagger.json
- independent-publisher-connectors/Finnish BIS/apiProperties.json
> Finnish BIS (Independent Publisher)

- independent-publisher-connectors/Clockify/README.md
- independent-publisher-connectors/Clockify/apiDefinition.swagger.json
- independent-publisher-connectors/Clockify/apiProperties.json
> Clockify (Independent Publisher)

- independent-publisher-connectors/icanhazdadjoke/apiDefinition.swagger.json
Add new action to icanhazdadjoke connector. Fetch a joke by Joke ID. Also, exposed Joke ID param from other actions as well.
---
> icanhazdadjoke v1.1 (Independent Publisher) - Add a new action to connector

- independent-publisher-connectors/Miro/Readme.md
- independent-publisher-connectors/Miro/apiDefinition.swagger.json
> Update Miro connector with additional operations (Independent Publisher)

- certified-connectors/MAQTextAnalytics/Readme.md
- certified-connectors/MAQTextAnalytics/apiDefinition.swagger.json
- certified-connectors/MAQTextAnalytics/apiProperties.json
> MAQTextAnalytics (Non-Microsoft Publisher)

- certified-connectors/RecordedFutureIdentity/README.md
- certified-connectors/RecordedFutureIdentity/apiDefinition.swagger.json
- certified-connectors/RecordedFutureIdentity/apiProperties.json
> Add Recorded Future Identity Connector

- certified-connectors/JG Integrations/apiDefinition.swagger.json
Default value for Regex Replace has been update from null to ""
Default response for PDF converse has been updated from string to object
---
> Modify default responses

- certified-connectors/RescoCloud/apiDefinition.swagger.json
> 19219 fix logic apps connector

- certified-connectors/Muhimbi PDF Converter Online/apiDefinition.swagger.json
Added new actions for Muhimbi connector
---
> Updated apiDefinition.swagger.json file

- certified-connectors/Cascade/apiDefinition.swagger.json
- certified-connectors/Cascade/apiProperties.json
- certified-connectors/Cascade/readme.md
> Added Cascade directory to certified-connector to verify

- certified-connectors/CRMBot/apiDefinition.swagger.json
- certified-connectors/CRMBot/apiProperties.json
> Update CRM Bot connector definition

- certified-connectors/CyberProof/apiDefinition.swagger.json
- certified-connectors/CyberProof/apiProperties.json
> Adding CyberProof connector Webhook trigger support and semantic changes

- certified-connectors/Vineforce/apiProperties.json
Updated Brand color for matching it with iconbrandcolor for certification
> Updated Brand Color

- independent-publisher-connectors/XSOAR/.gitignore
- independent-publisher-connectors/XSOAR/Readme.md
- independent-publisher-connectors/XSOAR/apiDefinition.swagger.json
- independent-publisher-connectors/XSOAR/apiProperties.json
> XSOAR (Independent Publisher)

- independent-publisher-connectors/Sessionize/apiDefinition.swagger.json
- independent-publisher-connectors/Sessionize/apiProperties.json
- independent-publisher-connectors/Sessionize/readme.md
Connector uses No authentication.
> Sessionize (Independent Publisher)

- independent-publisher-connectors/Udemy/apiDefinition.swagger.json
- independent-publisher-connectors/Udemy/apiProperties.json
- independent-publisher-connectors/Udemy/readme.md
Connector uses Basic Auth, not OAuth.
> Udemy (Independent Publisher)

- certified-connectors/jbhunt/README.md
- certified-connectors/jbhunt/Script.csx
- certified-connectors/jbhunt/apiDefinition.swagger.json
- certified-connectors/jbhunt/apiProperties.json
> Added JBHunt connector

- certified-connectors/CognitiveServicesQuestionAnswering/apiProperties.json
> Revert iconBrandColor

- certified-connectors/FlowForma V2/README.md
- certified-connectors/FlowForma V2/apiDefinition.swagger.json
- certified-connectors/FlowForma V2/apiProperties.json
> FlowForma V2

- certified-connectors/Vonage/README.md
- certified-connectors/Vonage/apiDefinition.swagger.json
- certified-connectors/Vonage/apiProperties.json
Adding Certified Vonage connector
> Adding Vonage connector

- certified-connectors/PDFcross/apiDefinition.swagger.json
- certified-connectors/PDFcross/apiProperties.json
- certified-connectors/PDFcross/readme.md
> add pdfcross connector

- independent-publisher-connectors/Star Wars/apiDefinition.swagger.json
fix page param and use param in swagger for #1624
---
- [*] I attest that the connector works and I verified by deploying and testing all the operations. 
- [*] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [*] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [*] I …
> Star Wars (Independent Publisher) fix for #1624

- certified-connectors/RecordedFutureIdentity/apiProperties.json
> RecordedFutureIdentity: Modify iconBrandColor to match new connector icon

- certified-connectors/CognitiveServicesQuestionAnswering/apiProperties.json
> Enabled Multi-auth (AAD and ApiKey)

- certified-connectors/IronDefense/apiDefinition.swagger.json
> Add host to apiDefinition.swagger.json

- certified-connectors/SmartCOMM On Demand Doc-Gen/apiDefinition.swagger.json
- certified-connectors/SmartCOMM On Demand Doc-Gen/script.csx
> Submit SmartCOMM On Demand Doc-Gen fixes for certification

- certified-connectors/RecordedFutureIdentity/apiDefinition.swagger.json
> Fix faulty property type in RecordedFutureIdentity connector response

- certified-connectors/Mobsim Send SMS/README.md
- certified-connectors/Mobsim Send SMS/apiDefinition.swagger.json
- certified-connectors/Mobsim Send SMS/apiProperties.json
Custom Connector for assessment.
---
> Certified Connector First Pull

- certified-connectors/CognitiveServicesQuestionAnswering/apiProperties.json
> Add connectionParameters in ApiProperties file

- certified-connectors/ShortURL/apiDefinition.swagger.json
- certified-connectors/ShortURL/readme.md
> Short URL v2

- certified-connectors/Azure Communication Services Identity/README.md
- certified-connectors/Azure Communication Services Identity/apiDefinition.swagger.json
- certified-connectors/Azure Communication Services Identity/apiProperties.json
- certified-connectors/Azure Communication Services Identity/script.csx
> Azure Communication Services Identity (Certified Connector)

- certified-connectors/ProcessStreet/README.md
- certified-connectors/ProcessStreet/apiDefinition.swagger.json
> Process Street - connector updates v1.1.5

- certified-connectors/envoy/apiDefinition.swagger.json
> preregistration-complete is string

- certified-connectors/Azure Communication Services Email/README.md
- certified-connectors/Azure Communication Services Email/apiDefinition.swagger.json
- certified-connectors/Azure Communication Services Email/apiProperties.json
- certified-connectors/Azure Communication Services Email/script.csx
> Azure Communication Services Email (Certified Connector)

- certified-connectors/dvelop/README.md
- certified-connectors/dvelop/apiDefinition.swagger.json
- certified-connectors/dvelop/apiProperties.json
---
- [ x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x ] I validated the …
> dvelop Version 2.0

- certified-connectors/Zvanu parvaldnieks/Readme.md
- certified-connectors/Zvanu parvaldnieks/apiDefinition.swagger.json
- certified-connectors/Zvanu parvaldnieks/apiProperties.json
---
- [x ] I validated the swagger file, …
> added Zvanu Parvaldnieks

- certified-connectors/Azure Communication Services Identity/apiProperties.json
> [Azure Communication Services Identity (Certified Connector)] Change icon brand color

- independent-publisher-connectors/Rijksoverheid/apiDefinition.swagger.json
- independent-publisher-connectors/Rijksoverheid/apiProperties.json
- independent-publisher-connectors/Rijksoverheid/readme.md
---
Tests of the new connector.
> Rijksoverheid (Independent Publisher)

- independent-publisher-connectors/Schiphol Airport/Readme.md
- independent-publisher-connectors/Schiphol Airport/apiDefinition.swagger.json
- independent-publisher-connectors/Schiphol Airport/apiProperties.json
---
- [ x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid …
> Schiphol Airport (Independent Publisher)

- certified-connectors/ZohoSign/apiDefinition.swagger.json
- certified-connectors/ZohoSign/apiProperties.json
- certified-connectors/ZohoSign/readme.md
> certified connector files created

- certified-connectors/Repfabric Lead Loader/Readme.md
- certified-connectors/Repfabric Lead Loader/apiDefinition.swagger.json
- certified-connectors/Repfabric Lead Loader/apiProperties.json
> Push Commit

- certified-connectors/Telnyx SMS/apiDefinition.swagger.json
- certified-connectors/Telnyx SMS/apiProperties.json
- certified-connectors/Telnyx SMS/readme.md
> Certified connector/telnyx sms conn

- certified-connectors/PPM Express/Readme.md
- certified-connectors/PPM Express/apiDefinition.swagger.json
- certified-connectors/PPM Express/apiProperties.json
> PPM Express connector init commit

- certified-connectors/Rainbird/Readme.md
- certified-connectors/Rainbird/apiDefinition.swagger.json
- certified-connectors/Rainbird/apiProperties.json
> added Rainbird connector in certified repo

- certified-connectors/Azure Communication Services Chat/README.md
- certified-connectors/Azure Communication Services Chat/apiDefinition.swagger.json
> [Azure Communication Services Chat (Certified Connector)]Updates based on Bug Bush feedbacks

- custom-connectors/Snowflake/apiDefinition.swagger.json
- custom-connectors/Snowflake/script.csx
---
Added domain as an operation parameter as per the developer's request.
> Add Snowflake Domain as an Operation Parameter

- certified-connectors/DocToPDF/Readme.md
- certified-connectors/DocToPDF/apiDefinition.swagger.json
- certified-connectors/DocToPDF/apiProperties.json
---
- [ X] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X ] I validated the …
> init submit DocToPDF

- certified-connectors/CloudConvert/apiDefinition.swagger.json
- certified-connectors/CloudConvert/apiProperties.json
- certified-connectors/CloudConvert/readme.md
> Add CloudConvert Connector

- certified-connectors/Delinea Secret Server/apiDefinition.swagger.json
- certified-connectors/Delinea Secret Server/apiProperties.json
- certified-connectors/Delinea Secret Server/readme.md
> Delinea Secret Server Connector

- certified-connectors/Azure Communication Services Email/README.md
- certified-connectors/Azure Communication Services Email/apiDefinition.swagger.json
- certified-connectors/Azure Communication Services Email/script.csx
> [Azure Communication Services Email (Certified Connector)] Updates based on Bug Bush feedbacks

- certified-connectors/Connect2All On-Premises/apiDefinition.swagger.json
- certified-connectors/Connect2All On-Premises/apiProperties.json
- certified-connectors/Connect2All On-Premises/readme.md
Added new connector 'Connect2All On-Premises'.
Updated readme of existing connector 'Connect2All'.
> Added Connect2All On-Premises

- certified-connectors/PDFco/apiDefinition.swagger.json
- certified-connectors/PDFco/apiProperties.json
- certified-connectors/PDFco/readme.md
> PR for PDFco Certified Connector

- certified-connectors/airSlate/apiDefinition.swagger.json
---
If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u).
> Add airSlate event subscription and unsubscription

- certified-connectors/Airmeet/Readme.md
- certified-connectors/Airmeet/apiDefinition.swagger.json
- certified-connectors/Airmeet/apiProperties.json
- certified-connectors/Airmeet/script.csx
> [AK] Added region support, question and answer and booth attendance

- certified-connectors/CivicPlus/apiDefinition.swagger.json
- certified-connectors/OneBlink/apiDefinition.swagger.json
> OneBlink & CivicPlus 

- independent-publisher-connectors/Schiphol Airport/apiDefinition.swagger.json
> Schiphol Airport (Independent Publisher) - Added Response metadata.

- independent-publisher-connectors/GoQR/apiDefinition.swagger.json
- independent-publisher-connectors/GoQR/apiProperties.json
- independent-publisher-connectors/GoQR/readme.md
Updated artifacts for GoQR IP Connector
Changed parameter required/not required. Added few more paramater (e.g. colour, file format)
---
> Updated action description for GoQR

- independent-publisher-connectors/VIES by European Commission/Readme.md
- independent-publisher-connectors/VIES by European Commission/apiDefinition.swagger.json
- independent-publisher-connectors/VIES by European Commission/apiProperties.json
- independent-publisher-connectors/VIES by European Commission/script.csx
This is my first time I tried writing custom code, but it works! Please, let me know if its ok.
I had to do it, because VIES service works only via SOAP, so I had to create code that forwards request to SOAP and returns results.
---
> VIES by European Commission (Independent Publisher)

- tools/paconn-cli/paconn/__init__.py
- tools/paconn-cli/setup.py
> Increment paconn version to update in PyPI

- independent-publisher-connectors/Finnish BIS/apiDefinition.swagger.json
- independent-publisher-connectors/MS Graph Groups and Users/apiDefinition.swagger.json
- independent-publisher-connectors/MS Graph Groups and Users/apiProperties.json
- independent-publisher-connectors/MS Graph Groups and Users/readme.md
> MS Graph Groups and Users (Independent Publisher)

- independent-publisher-connectors/Nationalize.io/Readme.md
- independent-publisher-connectors/Nationalize.io/apiDefinition.swagger.json
- independent-publisher-connectors/Nationalize.io/apiProperties.json
- independent-publisher-connectors/Nationalize.io/script.csx
> Nationalize.io (Independent Publisher)

- certified-connectors/DocJuris/apiDefinition.swagger.json
---
- [ x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ x] I validated the …
> DocJuris 3.2- Add ScreeningReportUpdated subscription

- certified-connectors/Yarado/Readme.md
- certified-connectors/Yarado/apiDefinition.swagger.json
- certified-connectors/Yarado/apiProperties.json
> Yarado connector - initial version

- certified-connectors/DomainToolsIrisEnrich/apiProperties.json
- certified-connectors/DomainToolsIrisInvestigate/apiProperties.json
> Updated Properties Files

- custom-connectors/Snowflake/apiDefinition.swagger.json
- custom-connectors/Snowflake/apiProperties.json
- custom-connectors/Snowflake/script.csx
---
Adds the convert operation for custom code, and adds fixes to existing issues with custom code.
> [Snowflake] Add Convert Operation and Improve Script

- certified-connectors/Microsoft Bookings/apiDefinition.swagger.json
> Description changes & Contact Info changes

- certified-connectors/IA-Connect Session/apiDefinition.swagger.json
Updated Swagger for IA-Connect 9.3 release (previous version is 9.2)
SetMouseMultiplier new input ApplyToCurrentMouseMoveMethod. If this input is not provided, the API acts as per the previous version (i.e. won't break existing flows)
A few minor description updates where there was a fault in the previous description
Added UnlockSession, LockSession, IsSessionLocked
Added GetGenericCredentialFromOrchestrator
Renamed friendly name "Get Orchestrator Flow stats" to "Get Flows stats from Orchestrator" (underlying API name not changed)
Added GetOrchestratorWorkerAvailabilityStats, GetOrchestratorWorkerFlowUsageHeatmap
---
If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwv …
> Updated Swagger for IA-Connect 9.3 release

- certified-connectors/Meisterplan/apiDefinition.swagger.json
- certified-connectors/Meisterplan/script.csx
- Meisterplan REST API now supports allocation entity to be resolved by key or name. Applied this change to the API definition file.
- added script file so it is added to archive in ISV Studio. The script redirects the api calls to the correct region in case the connector is using OAuth authentication flow
---
> Meisterplan Connector Update: Added Script File and Applied Latest REST API Definition

- certified-connectors/Zvanu parvaldnieks/Readme.md
- certified-connectors/Zvanu parvaldnieks/apiDefinition.swagger.json
> added delete webhook request

- certified-connectors/Vocean/Readme.md
- certified-connectors/Vocean/apiDefinition.swagger.json
- certified-connectors/Vocean/apiProperties.json
---
- [X ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X ] I validated the …
> Added Vocean to certified-connectors

- certified-connectors/CloudConvert/apiDefinition.swagger.json
- certified-connectors/CloudConvert/readme.md
Adds a new „Merge Files“ action to the existing, certified CloudConvert connector.
---
> Update CloudConvert connector

- certified-connectors/DQ on Demand/apiDefinition.swagger.json
- certified-connectors/DQ on Demand/apiProperties.json
- certified-connectors/DQ on Demand/readme.md
> DQ on Demand (Certified Connector)

- certified-connectors/iManage Work/apiDefinition.swagger.json
- certified-connectors/iManage Work/apiProperties.json
- certified-connectors/iManage Work/readme.md
> iManage Work (Certified Connector)

- certified-connectors/Pling/apiDefinition.swagger.json
- certified-connectors/Pling/apiProperties.json
- certified-connectors/Pling/readme.md
> Pling connector files

- certified-connectors/CivicPlus/apiDefinition.swagger.json
- certified-connectors/OneBlink/apiDefinition.swagger.json
> OneBlink & CivicPlus v1.4

- certified-connectors/PowerAssist/Readme.md
- certified-connectors/PowerAssist/apiDefinition.swagger.json
- certified-connectors/PowerAssist/apiProperties.json
> Power Assist - Certification

- certified-connectors/Verified/apiDefinition.swagger.json
We added NotificationMethod to the existing Verified connector
---
> Adding NotificationMethod to Verified Connector

- certified-connectors/ProcessStreet/apiDefinition.swagger.json
This is not a breaking change, we are lifting the 'required' constraint for a request parameter.
---
> Process Street: lift a required constraint for a POST parameter

- certified-connectors/DocumentTranslator/README.md
- certified-connectors/DocumentTranslator/apiDefinition.swagger.json
- certified-connectors/DocumentTranslator/apiProperties.json
Adding Document Translator connector
> Adding document translator connector

- certified-connectors/DocumentTranslator/apiProperties.json
Updating connection parameter properties for setting Host URL.
This update is tested
> Updating connection parameter properties for setting Host URL

- certified-connectors/Jupyrest/Readme.md
- certified-connectors/Jupyrest/apiDefinition.swagger.json
- certified-connectors/Jupyrest/apiProperties.json
> Jupyrest connector certification

- independent-publisher-connectors/ReliefWeb/apiDefinition.swagger.json
- independent-publisher-connectors/ReliefWeb/apiProperties.json
- independent-publisher-connectors/ReliefWeb/readme.md
> ReliefWeb (Independent Publisher)

- certified-connectors/Text Request/apiDefinition.swagger.json
- certified-connectors/Text Request/apiProperties.json
- certified-connectors/Text Request/readme.md
---
~If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:~
> Add Text Request connector files

- certified-connectors/Tesseron ASM Ticket/apiDefinition.swagger.json
> Tesseron ASM Update

- certified-connectors/Dynamics 365 Translation Service/Readme.md
- certified-connectors/Dynamics 365 Translation Service/apiDefinition.swagger.json
- certified-connectors/Dynamics 365 Translation Service/apiProperties.json
---
- [X ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X ] I validated the …
> Dynamics Translation Service (Certified Publisher)

- independent-publisher-connectors/SOS Inventory/README.md
- independent-publisher-connectors/SOS Inventory/apiDefinition.swagger.json
- independent-publisher-connectors/SOS Inventory/apiProperties.json
> SOS Inventory (independent publisher)

- independent-publisher-connectors/OpenAI/apiDefinition.swagger.json
Added contact info to OpenAI connector
> Added contact info to OpenAI connector

- independent-publisher-connectors/Near Earth Object Web Service/apiDefinition.swagger.json
- independent-publisher-connectors/Near Earth Object Web Service/apiProperties.json
- independent-publisher-connectors/Near Earth Object Web Service/readme.md
> Near Earth Object Web Service (Independent Publisher)

- certified-connectors/Secib/README.md
- certified-connectors/Secib/apiDefinition.swagger.json
> Secib - adding new operations (Certified Connector)

- certified-connectors/Connect2All On-Premises/apiDefinition.swagger.json
- certified-connectors/Connect2All/apiDefinition.swagger.json
Added Synchronous action to Connect2All connector.
Added Synchronous action to Connect2All on-premises connector.
> Connect2All - Synchronous action

- certified-connectors/Text Request/apiDefinition.swagger.json
> Make some Text Request parameters optional

- certified-connectors/PowerToolsLITE/apiDefinition.swagger.json
- certified-connectors/PowerToolsLITE/apiProperties.json
- certified-connectors/PowerToolsLITE/readme.md
- New host and base URL
- New apiKey header value
- Updated references
- New 'Collections' and 'Math' operations
- Added examples for all operations
---
- [ x] I attest that the connector ~~doesn't exist on the Power Platform today~~ is a new version of an existing connector. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ x] I attest that I have added detailed …
> Update to PowerTools LITE version 3.0

- independent-publisher-connectors/USGS Earthquake Hazards/apiDefinition.swagger.json
- independent-publisher-connectors/USGS Earthquake Hazards/apiProperties.json
- independent-publisher-connectors/USGS Earthquake Hazards/readme.md
> USGS Earthquake Hazards (Independent Publisher)

- independent-publisher-connectors/You Need A Budget/apiDefinition.swagger.json
- independent-publisher-connectors/You Need A Budget/apiProperties.json
- independent-publisher-connectors/You Need A Budget/readme.md
> You Need A Budget (Independent Publisher)

- certified-connectors/Connect2All On-Premises/apiDefinition.swagger.json
- certified-connectors/Connect2All/apiDefinition.swagger.json
We now use a gateway so we needed to change the host name.
> Connect2All: changed host name

- certified-connectors/UiPath Orchestrator/ReadMe.md
- certified-connectors/UiPath Orchestrator/apiDefinition.swagger.json
- certified-connectors/UiPath Orchestrator/apiProperties.json
Contains v1.0.0 of the UiPath Connector which we are submitting for certification.
> UiPath Orchestrator

- independent-publisher-connectors/Connpass/Readme.md
- independent-publisher-connectors/Connpass/apiDefinition.swagger.json
- independent-publisher-connectors/Connpass/apiProperties.json
> Connpass (Independent Publisher)

- certified-connectors/Cloud BOT/Readme.md
- certified-connectors/Cloud BOT/apiDefinition.swagger.json
- certified-connectors/Cloud BOT/apiProperties.json
> Cloud BOT (Certified Connector)

- certified-connectors/LMS365/apiDefinition.swagger.json
Added missing session enrollment type option
#18599
---
> Added "EnrollToMultiple" session enrollment type

- certified-connectors/BiG EVAL/Readme.md
- certified-connectors/BiG EVAL/apiDefinition.swagger.json
- certified-connectors/BiG EVAL/apiProperties.json
> BiG EVAL (Certified Connector)

- certified-connectors/N-able Cloud User Hub/apiDefinition.swagger.json
- certified-connectors/N-able Cloud User Hub/apiProperties.json
- certified-connectors/N-able Cloud User Hub/readme.md
> N able cloud user hub cert validation

- certified-connectors/timeghost/apiDefinition.swagger.json
> timeghost: Add project template

- certified-connectors/InfoQuery Title Explorer/README.md
- certified-connectors/InfoQuery Title Explorer/apiDefinition.swagger.json
- certified-connectors/InfoQuery Title Explorer/apiProperties.json
> Initial commit.

- certified-connectors/AzureDigitalTwins/Readme.md
- certified-connectors/AzureDigitalTwins/apiDefinition.swagger.json
- certified-connectors/AzureDigitalTwins/apiProperties.json
- certified-connectors/AzureDigitalTwins/connector-script.csx
> initial commit for Azure Digital Twins

- independent-publisher-connectors/Owlbot/apiDefinition.swagger.json
- independent-publisher-connectors/Owlbot/apiProperties.json
- independent-publisher-connectors/Owlbot/readme.md
> Owlbot (Independent Publisher)

- independent-publisher-connectors/HTTP Garden/apiDefinition.swagger.json
- independent-publisher-connectors/HTTP Garden/apiProperties.json
- independent-publisher-connectors/HTTP Garden/readme.md
> HTTP Garden (Independent Publisher)

- certified-connectors/HYAS Insight/apiDefinition.swagger.json
- certified-connectors/HYAS Insight/apiProperties.json
- certified-connectors/HYAS Insight/readme.md
> Updated HYAS Insight

- certified-connectors/Projectplace/apiDefinition.swagger.json
- certified-connectors/Projectplace/apiProperties.json
- certified-connectors/Projectplace/readme.md
No actual changes - just the rebranding of Planview Projectplace to camel case ProjectPlace.
Also took the time to update some of the swagger definition file to refer to "activities" rather than "planlets". The word "planlet" is really internal to Projectplace - while the word "activity" is understandable by an end user.
---
- [] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
If you are an …
> Rebranding of Projectplace to ProjectPlace

- certified-connectors/Morf/Readme.md
- certified-connectors/Morf/apiDefinition.swagger.json
- certified-connectors/Morf/apiProperties.json
Submission for certification of the [Morf](http://getmorf.io/) connector.
---
> Adding Morf (certified-connectors)

- certified-connectors/LMS365/apiDefinition.swagger.json
Change the order of the enum values so that the new one is added to the bottom of the list
---
> Fix json schema for LMS365 (Certified connector) v2

- independent-publisher-connectors/Focusmate/apiDefinition.swagger.json
- independent-publisher-connectors/Focusmate/apiProperties.json
- independent-publisher-connectors/Focusmate/readme.md
Note: When testing I got schema validation because of formats, 'uuid', 'uri', 'date-time'.  There are many other instance of those schema types being used within the PowerPlatformConnectors repo, so I'm assuming they're OK, but please let me know if otherwise.
Definition:
Test run:
Definition:
Test run:
Definition:
Test run:
> Focusmate (Independent Publisher)

- certified-connectors/Tesseron ASM Basic Data/apiDefinition.swagger.json
- certified-connectors/Tesseron ASM Ticket/apiDefinition.swagger.json
> Title Changes

- certified-connectors/Business Assist/README.md
- certified-connectors/Business Assist/apiDefinition.swagger.json
- certified-connectors/Business Assist/apiProperties.json
- certified-connectors/Business Assist/script.csx
> Submitting Business Assist connector for certification

- certified-connectors/PDFcross/apiDefinition.swagger.json
- certified-connectors/PDFcross/readme.md
> pdfcross update connector (add image api)

- certified-connectors/3E Events/apiDefinition.swagger.json
> add 3 new Template Platform actions

- independent-publisher-connectors/Electricity Maps/Readme.md
- independent-publisher-connectors/Electricity Maps/apiDefinition.swagger.json
- independent-publisher-connectors/Electricity Maps/apiProperties.json
> Electricity Maps (Independent Publisher)

- certified-connectors/Dime.Scheduler/README.md
- certified-connectors/Dime.Scheduler/apiDefinition.swagger.json
- certified-connectors/Dime.Scheduler/apiProperties.json
> Dime.Scheduler (Certified Connector)

- certified-connectors/Plumsail Forms/Readme.md
- certified-connectors/Plumsail Forms/apiDefinition.swagger.json
> Added Download attachment action to Plumsail Forms connector

- certified-connectors/AzureDigitalTwins/apiDefinition.swagger.json
- certified-connectors/AzureDigitalTwins/apiProperties.json
- certified-connectors/AzureDigitalTwins/connector-script.csx
1. Add continuationToken as optional parameter for ListRelationships/ListIncomingRelationships/ListModels API;
2. Add continuationToken Handler in the script;
3. Fix typo;
4. Remove updatenextlink policy;
---
> Add Pagination feature

- certified-connectors/AzureDigitalTwins/apiDefinition.swagger.json
---
From AzureDigitalTwinsFPAAustin to Azure Digital Twins
> Connector title issue fix

- certified-connectors/Microsoft Bookings/apiDefinition.swagger.json
> Added 2 new fields to be returned as a part of connector notification

- certified-connectors/MongoDB/apiDefinition.swagger.json
The base url had changed to an actual one in last commit. Corrected the same.
---
> Changed Base url to a templatised one

- certified-connectors/Oodrive Sign/apiDefinition.swagger.json
- certified-connectors/Oodrive Sign/apiProperties.json
- certified-connectors/Oodrive Sign/readme.md
> Adding Oodrive Sign connector (certified-connectors)

- certified-connectors/Meisterplan/apiDefinition.swagger.json
- certified-connectors/Meisterplan/apiProperties.json
- added new internal endpoints for schema and user connection information
- added x-ms-dynamic-schema extension to definitions that can have dynamic fields
- applied new swagger json file of rest api (added actuals costType and costPerHour)
- added x-ms-capabilities testConnection to swagger file
- applied new brand color to apiProperties
---
> Meisterplan Connector: Added support for dynamic schema in swagger file

- certified-connectors/DeepL/apiDefinition.swagger.json
- certified-connectors/DeepL/apiProperties.json
- certified-connectors/DeepL/readme.md
---
The connector does exist from an Individual Publisher but not from us as DeepL officially.
> Commit DeepL connector

- certified-connectors/tegolySIGN/apiDefinition.swagger.json
- certified-connectors/tegolySIGN/apiProperties.json
- certified-connectors/tegolySIGN/readme.md
> First version of the tegolySIGN connector

- certified-connectors/Encodian/Readme.md
- certified-connectors/Encodian/apiDefinition.swagger.json
> Encodian October 22 Release #2

- independent-publisher-connectors/One-Time Secret/README.md
- independent-publisher-connectors/One-Time Secret/apiDefinition.swagger.json
- independent-publisher-connectors/One-Time Secret/apiProperties.json
---
- [X ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ X] I validated the …
> One-Time Secret (Independent Publisher)

- independent-publisher-connectors/De Lijn/De-Lijn-Zoek.swagger.json
- independent-publisher-connectors/De Lijn/apiProperties.json
- independent-publisher-connectors/De Lijn/readme.md
---
- [x ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding.
> De Lijn (Independent Publisher)

- certified-connectors/Zuva DocAI/README.md
- certified-connectors/Zuva DocAI/apiDefinition.swagger.json
- certified-connectors/Zuva DocAI/script.csx
- Coalesce null "Extractions" to an empty array, so that the user doesn't always have to check for null values
- Rename GetAllFields to GetFieldList for clarity
---
> Update Zuva DocAI connector

- certified-connectors/Zuva DocAI/README.md
- certified-connectors/Zuva DocAI/apiDefinition.swagger.json
- certified-connectors/Zuva DocAI/script.csx
> Zuva DocAI - add Normalization and Multi-Level Classification endpoints

- certified-connectors/UiPath Orchestrator/apiDefinition.swagger.json
- certified-connectors/UiPath Orchestrator/apiProperties.json
1. Updated resource URLs from "staging" to "cloud".
2. Added "Required. " prefix on descriptions for required fields.
---
> Updated resource URLs to production, updated required field descriptions

- certified-connectors/Microsoft Bookings/apiDefinition.swagger.json
---
Updating the connector to not show a email contact and reach out to Bookings via M365 support.
> Updated connector contact info

- certified-connectors/bitskout/Readme.md
- certified-connectors/bitskout/apiDefinition.swagger.json
- certified-connectors/bitskout/apiProperties.json
> Bitskout Connector

- independent-publisher-connectors/Google Books/apiDefinition.swagger.json
- independent-publisher-connectors/Google Books/apiProperties.json
- independent-publisher-connectors/Google Books/readme.md
> Google Books (Independent Publisher)

- certified-connectors/axiom.ai/Readme.md
- certified-connectors/axiom.ai/apiDefinition.swagger.json
- certified-connectors/axiom.ai/apiProperties.json
Hello, 
This is a connector for axiom.ai, created by axiom.ai, so we're assuming it can be a certified connector. 
Please let us know if we need to do anything else for certified status. 
---
> axiom.ai certified connector

- certified-connectors/Emigo/Readme.md
- certified-connectors/Emigo/apiDefinition.swagger.json
- certified-connectors/Emigo/apiProperties.json
> Add Emigo Connector

- certified-connectors/LnkBio/Readme.md
- certified-connectors/LnkBio/apiDefinition.swagger.json
- certified-connectors/LnkBio/apiProperties.json
Lnk.Bio Certified Connector
---
- [ x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand …
> Initial Release of the Lnk.Bio certified connector

- certified-connectors/EBMS/README.md
- certified-connectors/EBMS/apiDefinition.swagger.json
- certified-connectors/EBMS/apiProperties.json
- [*] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [*] I attest that the connector works and I verified by deploying and testing all the operations. 
- [*] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [*] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [*] I validated the swagger …
> Continuing work for Eagle connector.

- certified-connectors/Team Forms/README.md
- certified-connectors/Team Forms/apiDefinition.swagger.json
- certified-connectors/Team Forms/apiProperties.json
> Add Team Forms certified connector

- certified-connectors/AzureDigitalTwins/apiDefinition.swagger.json
- certified-connectors/AzureDigitalTwins/apiProperties.json
- certified-connectors/AzureDigitalTwins/connector-script.csx
> Update API enhancement

- certified-connectors/Azure Communication Services SMS Events/README.md
- certified-connectors/Azure Communication Services SMS Events/apiDefinition.swagger.json
- certified-connectors/Azure Communication Services SMS Events/apiProperties.json
- certified-connectors/Azure Communication Services SMS Events/script.csx
> Azure Communication Services SMS Events (Certified Connector)

- certified-connectors/Business Assist/apiDefinition.swagger.json
[BusinessAssist] Updated Selfhelp operation
---
> [BusinessAssist] Updated Selfhelp operation

- certified-connectors/Unearth Ingest/apiDefinition.swagger.json
- certified-connectors/Unearth Ingest/apiProperties.json
- certified-connectors/Unearth Ingest/readme.md
> Unearth Ingest (Certified Connector)

- independent-publisher-connectors/TSheets Quickbooks Time/apiDefinition.swagger.json
- independent-publisher-connectors/TSheets Quickbooks Time/apiProperties.json
- independent-publisher-connectors/TSheets Quickbooks Time/readme.md
We have searched and there is no connector for the above mentioned product. We would like to develop and share this to Power Platform community.
> TSheets Quickbooks Time (Independent Publisher)

- independent-publisher-connectors/FishWatch/apiDefinition.swagger.json
- independent-publisher-connectors/FishWatch/apiProperties.json
- independent-publisher-connectors/FishWatch/readme.md
> FishWatch (Independent Publisher)

- independent-publisher-connectors/Pixel Encounter/apiDefinition.swagger.json
- independent-publisher-connectors/Pixel Encounter/apiProperties.json
- independent-publisher-connectors/Pixel Encounter/readme.md
> Pixel encounter (Independent Publisher)

- certified-connectors/MongoDB/apiDefinition.swagger.json
- certified-connectors/MongoDB/apiProperties.json
> Diana mdb preview test 1

- certified-connectors/Azure Communication Services SMS Events/apiProperties.json
> Fix apiProperties issue

- independent-publisher-connectors/SMS Wireless Services/apiDefinition.swagger.json
- independent-publisher-connectors/SMS Wireless Services/apiProperties.json
- independent-publisher-connectors/SMS Wireless Services/readme.md
> SMS Wireless Services (Independent Publisher)

- independent-publisher-connectors/ExchangeRate/apiDefinition.swagger.json
- independent-publisher-connectors/ExchangeRate/apiProperties.json
- independent-publisher-connectors/ExchangeRate/readme.md
> ExchangeRate (Independent Publisher)

- certified-connectors/WorkPoint/apiDefinition.swagger.json
> Update host for WorkPoint Connector

- certified-connectors/Seismic Configuration/apiDefinition.swagger.json
- certified-connectors/Seismic Configuration/apiProperties.json
- certified-connectors/Seismic Configuration/readme.md
> Seismic Configuration (Verified Publisher)

- certified-connectors/EBMS/README.md
- certified-connectors/EBMS/apiDefinition.swagger.json
- certified-connectors/EBMS/apiProperties.json
---
- [*] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [*] I attest that the connector works and I verified by deploying and testing all the operations. 
- [*] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [*] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [*] I validated the swagger …
> Continuing certification for EBMS - some minor changes.

- certified-connectors/Seismic Livedoc/apiDefinition.swagger.json
- certified-connectors/Seismic Livedoc/apiProperties.json
- certified-connectors/Seismic Livedoc/readme.md
> Seismic Livedoc (Verified Publisher)

- certified-connectors/Scrive eSign/apiDefinition.swagger.json
- certified-connectors/Scrive eSign/apiProperties.json
- certified-connectors/Scrive eSign/readme.md
> Update scrive esign 

- certified-connectors/Seismic Content Discovery/apiDefinition.swagger.json
- certified-connectors/Seismic Content Discovery/apiProperties.json
- certified-connectors/Seismic Content Discovery/readme.md
> Seismic Content Discovery (Verified Publisher)

- certified-connectors/Adobe Experience Manager/apiDefinition.swagger.json
- certified-connectors/Business Assist/apiDefinition.swagger.json
> iManage Work for Admins (certified-connector)

- independent-publisher-connectors/IQAir/apiDefinition.swagger.json
- independent-publisher-connectors/IQAir/apiProperties.json
- independent-publisher-connectors/IQAir/readme.md
> IQAir (Independent Publisher)

- independent-publisher-connectors/Swagger Converter/apiDefinition.swagger.json
- independent-publisher-connectors/Swagger Converter/apiProperties.json
- independent-publisher-connectors/Swagger Converter/readme.md
> Swagger Converter (Independent Publisher)

- certified-connectors/VitaCloud Quotes/Readme.md
- certified-connectors/VitaCloud Quotes/apiDefinition.swagger.json
- certified-connectors/VitaCloud Quotes/apiProperties.json
> VitaCloud Quotes

- certified-connectors/envoy/apiDefinition.swagger.json
> [Envoy] Update Connector Host

- certified-connectors/bitskout/apiProperties.json
> Changed the Icon color

- independent-publisher-connectors/Postman/apiDefinition.swagger.json
- independent-publisher-connectors/Postman/apiProperties.json
- independent-publisher-connectors/Postman/readme.md
> Postman (Independent Publisher)

- independent-publisher-connectors/Nederlandse Spoorwegen/apiDefinition.swagger.json
> Changed email

- certified-connectors/Meisterplan/apiDefinition.swagger.json
- certified-connectors/Meisterplan/readme.md
- added endpoint to create webhook for project event trigger
- added endpoint for dynamic notification schema
- added webhook delete endpoint
- added new absences endpoint
- added new resource manager field to resource and role endpoints
---
> Meisterplan Connector Update: New Project Trigger via Webhook Create

- certified-connectors/Encodian/Readme.md
- certified-connectors/Encodian/apiDefinition.swagger.json
- certified-connectors/Encodian/apiProperties.json
---
If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u).
> Encodian Jan 23

- certified-connectors/Narvar/apiDefinition.swagger.json
- certified-connectors/Narvar/apiProperties.json
- certified-connectors/Narvar/readme.md
---
- [*] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [*] I attest that the connector works and I verified by deploying and testing all the operations. 
- [*] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [*] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [*] I validated the swagger …
> Narvar Connector

- certified-connectors/Xpertdoc/apiDefinition.swagger.json
- certified-connectors/Xpertdoc/apiProperties.json
- certified-connectors/Xpertdoc/readme.md
We are deprecating this connector now that the Experlogix Smart Flows connector has been deployed to all regions.
> Deprecated Xpertdoc connector.

- certified-connectors/WQRM Risk Forecast Services/README.md
- certified-connectors/WQRM Risk Forecast Services/apiDefinition.swagger.json
- certified-connectors/WQRM Risk Forecast Services/apiProperties.json
---
- [X ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X ] I validated the …
> WQRM Risk Forecast Services

- certified-connectors/Azure Communication Services SMS Events/apiDefinition.swagger.json
> Fix the signin issue by removing testConnection

- certified-connectors/Seismic Configuration/apiDefinition.swagger.json
> Seismic content discovery: Corrected text

- certified-connectors/Seismic Livedoc/apiDefinition.swagger.json
> Seismic livedoc: Updated property names

- certified-connectors/NBG ERP Solution/apiDefinition.swagger.json
- certified-connectors/NBG ERP Solution/apiProperties.json
- certified-connectors/NBG ERP Solution/readme.md
Hello, 
As per our latest communication via e-mail, please note that we have uploaded the necessary files for the custom connector(apiDefinition.swagger.json,apiProperties.json, a Readme.md file). You may review these files so as to proceed later with the next steps (Upload from local files to ISV Studio). If there is anything else that you need from our side let us know. 
Thank you,
National Bank of Greece
---
> @microsoft-github-policy-service agree company="National Bank of Greece"

- certified-connectors/Seismic Engagement/apiDefinition.swagger.json
> SeismicEngagement:Added missing properties and update property names

- certified-connectors/Fliplet/README.md
- certified-connectors/Fliplet/apiDefinition.swagger.json
- certified-connectors/Fliplet/apiProperties.json
Hello,
I am the head of development at Fliplet. Following up from various emails with our Product owner, I have been asked to package and submit our connector.
**I'm attaching a few screenshots of the connector at the end of the PR.**
Please let me know if you have any questions.
---
---
> Fliplet Connector

- certified-connectors/Seismic Content Discovery/apiDefinition.swagger.json
> SeismicContentDiscovery:Updated property names and added missing properties

- independent-publisher-connectors/Annature/README.md
- independent-publisher-connectors/Annature/apiDefinition.swagger.json
- independent-publisher-connectors/Annature/apiProperties.json
- independent-publisher-connectors/Annature/script.csx
---
Note:
Delete Endpoint is a Trigger managed internally by the Webhook. But has been tested this webhook via Flow. Rest of the Actions are Tested from the Test Console.
> Annature (Independent Publisher)

- certified-connectors/OpenLegacy IBM I (AS400)/script.csx
> fix wrong operation name in script.csx

- certified-connectors/Mural/README.md
- certified-connectors/Mural/Script.cs
- certified-connectors/Mural/apiDefinition.swagger.json
- certified-connectors/Mural/apiProperties.json
> Updating Mural connector to v2

- certified-connectors/Mural/apiProperties.json
> Updating Mural brand color.

- independent-publisher-connectors/IBM Watson Text to Speech/apiDefinition.swagger.json
- independent-publisher-connectors/IBM Watson Text to Speech/apiProperties.json
- independent-publisher-connectors/IBM Watson Text to Speech/readme.md
- independent-publisher-connectors/IBM Watson Text to Speech/script.csx
- independent-publisher-connectors/IBM Watson Text to Speech/settings.json
> IBM Watson Text to Speech (Independent Publisher)

- independent-publisher-connectors/WhatsApp/ReadME.md
- independent-publisher-connectors/WhatsApp/apiDefinition.swagger.json
- independent-publisher-connectors/WhatsApp/apiProperties.json
> WhatsApp (Independent Publisher)

- certified-connectors/Seismic Engagement/apiDefinition.swagger.json
> SeismicEngagement: Added property summary and missing property

- certified-connectors/TranslatorV3/apiDefinition.swagger.json
Updating TranslatorV3 strings after PM reviews.
> Updating TranslatorV3 strings

- certified-connectors/Tesseron Invoice/apiDefinition.swagger.json
- certified-connectors/Tesseron Invoice/apiProperties.json
- certified-connectors/Tesseron Invoice/readme.md
> Tesseron Invoice Connector

- certified-connectors/Seismic Content Discovery/readme.md
> SeismicContentDiscovery: Updated readme file

- certified-connectors/Seismic Configuration/readme.md
> SeismicConfiguration: Updated readme file

- independent-publisher-connectors/Airlabs/apiDefinition.swagger.json
- independent-publisher-connectors/Airlabs/apiProperties.json
- independent-publisher-connectors/Airlabs/readme.md
> Airlabs (Independent Publisher)

- certified-connectors/DocuSign/apiDefinition.swagger.json
- certified-connectors/DocuSign/apiProperties.json
- certified-connectors/DocuSign/script.csx
---
- [x ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am …
> DS1001 - R1.Mar release from DocuSignDemo connector to DocuSign

- independent-publisher-connectors/SMS Wireless Services/apiProperties.json
Remove connectionParameter KEY
---
> Update - SMS Wireless Services (Independent Publisher)

- independent-publisher-connectors/PaySpace/README.md
- independent-publisher-connectors/PaySpace/apiDefinition.swagger.json
- independent-publisher-connectors/PaySpace/apiProperties.json
> PaySpace (Independent Publisher)

- certified-connectors/CivicPlus/apiDefinition.swagger.json
> CivicPlus (Certified Connector) v1.5

- certified-connectors/Seismic Livedoc/apiDefinition.swagger.json
- certified-connectors/Seismic Livedoc/readme.md
> SeismicLivedoc: Updated readme file

- certified-connectors/ActiveCampaign/README.md
- certified-connectors/ActiveCampaign/apiDefinition.swagger.json
- certified-connectors/ActiveCampaign/apiProperties.json
> Add ActiveCampaign Contacts connector

- certified-connectors/Fliplet/README.md
- certified-connectors/Fliplet/apiDefinition.swagger.json
Hello, 
I am the maintainer of the Fliplet certified connector. We had to make a minor change and remove one of the endpoints from the swagger definition.
Thanks
---
> [Chore] Removed one endpoint from Fliplet connector

- certified-connectors/Desk365/Readme.md
- certified-connectors/Desk365/apiDefinition.swagger.json
- certified-connectors/Desk365/apiProperties.json
> Initial version of the connector

- certified-connectors/RescoReports/README.md
- certified-connectors/RescoReports/apiDefinition.swagger.json
- certified-connectors/RescoReports/apiProperties.json
> Resco Reports connector artifacts

- certified-connectors/VitaCloud Quotes/Readme.md
- certified-connectors/VitaCloud Quotes/apiDefinition.swagger.json
- certified-connectors/VitaCloud Quotes/apiProperties.json
> VitaCloud Quotes Connector Updates

- certified-connectors/Advanced Data Operations/README.md
- certified-connectors/CyberProof/apiDefinition.swagger.json
> Added support for new CDC APIs in CyberProof connector

- certified-connectors/Survalyzer EU/README.md
- certified-connectors/Survalyzer EU/apiDefinition.swagger.json
- certified-connectors/Survalyzer EU/apiProperties.json
> Add Survalyzer EU Connector

- certified-connectors/Mural/Script.cs
- certified-connectors/Mural/apiDefinition.swagger.json
- certified-connectors/Mural/apiProperties.json
> Adding fixes for issues in preview environment during testing.

- certified-connectors/Seismic Library/apiDefinition.swagger.json
- certified-connectors/Seismic Library/apiProperties.json
- certified-connectors/Seismic Library/readme.md
> SeimicLibrary: Added library connector

- certified-connectors/Maximizer/apiDefinition.swagger.json
> updated swagger

- certified-connectors/NBG ERP Solution/apiDefinition.swagger.json
NBG ERP Solution Fix 20230407
---
> NBG ERP Solution Fix 20230407

- certified-connectors/Seismic Library/apiDefinition.swagger.json
- certified-connectors/Seismic Library/readme.md
> SeismicLibrary: Updated propertied and readme file

- certified-connectors/TranslatorV3/apiDefinition.swagger.json
- certified-connectors/TranslatorV3/script.csx
Adding Transliterated text in the output of Translate call
> Adding Transliterated text in the output of Translate call

- certified-connectors/Seismic Library/apiDefinition.swagger.json
> SeismicLibrarary:Updated property display names

- certified-connectors/FactSet/Readme.md
- certified-connectors/FactSet/apiDefinition.swagger.json
---
- [] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.
If you are an Independent Publisher, you must also attest to the following to …
> Updating ReadMe and apiDefinition for FactSet Connector

- custom-connectors/AzureOpenAIService/script.csx
> Fixes [BUG] Completion Action occasionally returns end token as part of answer #2563

- certified-connectors/LCP - iCordis/Readme.md
- certified-connectors/LCP - iCordis/apiDefinition.swagger.json
- certified-connectors/LCP - iCordis/apiProperties.json
> added LCP - iCordis connector

- certified-connectors/Integration Toolbox/apiDefinition.swagger.json
---
If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u).
> Deprecated all operations.

- independent-publisher-connectors/InstagramBasicDisplay/apiDefinition.swagger.json
- independent-publisher-connectors/InstagramBasicDisplay/apiProperties.json
- independent-publisher-connectors/InstagramBasicDisplay/readme.md
> Instagram basic display  (Independent Publisher)

- certified-connectors/Business Assist/apiDefinition.swagger.json
- certified-connectors/Business Assist/apiProperties.json
- certified-connectors/Business Assist/script.csx
> [Business Assist] Updated response schema/descriptions.

- certified-connectors/eformity/apiDefinition.swagger.json
- certified-connectors/eformity/apiProperties.json
- certified-connectors/eformity/readme.md
> Added eformity connector

- certified-connectors/Microsoft Bookings/Readme.md
- certified-connectors/Microsoft Bookings/apiDefinition.swagger.json
- certified-connectors/Microsoft Bookings/apiProperties.json
> Update Bookings connector to use new API and show a drop down in the Bookings trigger

- custom-connectors/Snowflake/script.csx
> Correcting bug with rowtype error. converting to resultsetmetadata

- certified-connectors/The IT Tipster/apiDefinition.swagger.json
- certified-connectors/The IT Tipster/apiProperties.json
- certified-connectors/The IT Tipster/readme.md
> The IT Tipster Pull Request

- certified-connectors/ModuleQ/apiDefinition.swagger.json
> ModuleQ deprecate NewRecTrigger

- certified-connectors/Seismic Workspace/apiDefinition.swagger.json
- certified-connectors/Seismic Workspace/apiProperties.json
- certified-connectors/Seismic Workspace/readme.md
> Seismic workspace (Verified publisher)

- certified-connectors/nps.today/apiDefinition.swagger.json
---
- [] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [] I attest that the connector works and I verified by deploying and testing all the operations. 
- [] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [] I validated the swagger …
> Updating POST body for webhook requests

- certified-connectors/Microsoft Bookings/apiDefinition.swagger.json
> Updates to some of the descriptions and summaries of our connector artifacts.

- certified-connectors/DocuMotor/apiDefinition.swagger.json
> DocuMotor update response type and tags

- certified-connectors/1Me Corporate/Readme.md
- certified-connectors/1Me Corporate/apiDefinition.swagger.json
- certified-connectors/1Me Corporate/apiProperties.json
> 1me Conrporate

- certified-connectors/LCP - iCordis/apiProperties.json
Update to the LCP - iCordis connector, added an extra scope for authentication.
> update LCP - iCordis - extra scope for authentication

- certified-connectors/Meisterplan/apiDefinition.swagger.json
- certified-connectors/Meisterplan/readme.md
- include financial actuals actions (get, get all, create, update, replace and delete)
- include Meisterplan user read actions
- added viewUrl property to project response
---
>  Meisterplan Connector: Update API definition file 
