microsoft/PowerPlatformConnectors

- .github/CODEOWNERS
Added codeowners for third party open source connectors
> Added codeowners for third party open source connectors

- tools/paconn-cli/paconn.pyproj
- tools/paconn-cli/paconn/authentication/profile.py
- tools/paconn-cli/paconn/commands/create.py
- tools/paconn-cli/paconn/commands/download.py
- tools/paconn-cli/paconn/commands/params.py
- tools/paconn-cli/paconn/commands/update.py
- tools/paconn-cli/paconn/common/util.py
- tools/paconn-cli/paconn/operations/download.py
- tools/paconn-cli/paconn/operations/upsert.py
- tools/paconn-cli/paconn/settings/settingsserializer.py
- tools/paconn-cli/paconn/settings/util.py
- Specified directory during download is created when doesn't exists, but no extra sub-drectory with connector_id is created.
- A sub-drectory with connector_id is still created when destination parameter isn't specified during download.
- A --overwrite option is added during download. When this is parameter specified ALL destination file will be overwritten. Customer will be prompted for file replacement when this parameter is not specified.
- A settings file is now written after the create operation.
- A --overwriter-setting option is added for create. When this is parameter specified the settings file will be overwritten. Customer will be prompted for settings file replacement when this parameter is not specified.
---
This checklist is used to make sure that common guidelines for a …
> Improved download and create connector experience

- certified-connectors/Way We Do/apiDefinition.swagger.json
- certified-connectors/Way We Do/readme.md
> [WayWeDo] Updating the outdated brand names

- certified-connectors/Stormboard/apiDefinition.swagger.json
> [Stormboard] Updating the updated brand names

- certified-connectors/Smarp/readme.md
> [Smarp] Updating the outdated brand names

- certified-connectors/Pushcut/readme.md
> [Pushcut] Updating the outdated brand names

- certified-connectors/Encodian/apiDefinition.swagger.json
> [Encodian] Updating outdated brand names

- certified-connectors/envoy/readme.md
> [Envoy] Updating outdated brand names

- certified-connectors/HotProfile/readme.md
> [HotProfile] Updating outdated brand names

- certified-connectors/LeadDesk/readme.md
> [LeadDesk] Updating the outdated brand names

- certified-connectors/Rencore Governance/readme.md
> [RencoreGovernance] Updating the outdated brand names

- certified-connectors/Robolytix/readme.md
> [Robolytix] Updating the outdated brand names

- .vscode/settings.json
- schemas/apiDefinition.swagger.schema.json
- schemas/paconn-apiProperties.schema.json
- schemas/paconn-settings.schema.json
[VS Code] Add schemas for common files
- settings.json (paconn settings file)
- apiProperties.json
- apiDefinition.swagger.json
The schema for apiDefinition.swagger.json files is modified from the one found at http://schemastore.org/json/. It includes many 'x-ms-' vendor extensions.
---
> [VS Code] Add schemas for common files

- certified-connectors/Slascone/apiDefinition.swagger.json
> [Slascone] Updating the outdated brand names

- schemas/apiDefinition.swagger.schema.json
- schemas/paconn-apiProperties.schema.json
- schemas/paconn-settings.schema.json
- Set our custom schemas so their ids point to the raw schema file.
The initial ids were to an html page. The new ids point to the raw file download.
- added support for the optional "$schema" property so loose files can still get intellisense.
Swagger schema updates:
- Added snippets for swagger $ref properties.
- Added support for `x-ms-pageable`
- Added support for `x-ms-enum-values`
- Added enum for `format`
apiProperties schema
- Added policy template `updatenextlink`
- Added some snippets for policy templates
- Remove erroneous definitions of `x-ms-apimTemplate-policySection`
---
> {VS Code} Update schemas

- certified-connectors/OutlookTasks/apiDefinition.swagger.json
- certified-connectors/OutlookTasks/apiProperties.json
- Fix folder and group operations
- add `x-ms-enum-values` where appropriate
- outlooktasks: set default value for $top
- add $filter parameter to collection endpoints
- add GetTaskGroup, UpdateTaskGroup
---
> [OutlookTasks] Add actions for managing Tasks and other fixes

- certified-connectors/CognitiveServicesTextAnalytics/apiDefinition.swagger.json
- certified-connectors/CognitiveServicesTextAnalytics/apiProperties.json
Now that Text Analytics v3.0 is available for GA, we can add the new endpoints and their corresponding functionality into the power platform connector - this does so, and has been tested locally as a custom connector (Text Analytics Preview V3). It maintains all the old endpoints as well, describing them as V2 endpoints, and the new endpoints are labeled as V3
> add the v3.0 GA endpoint to the Text Analytics connector

- certified-connectors/OutlookTasks/apiDefinition.swagger.json
- certified-connectors/OutlookTasks/apiProperties.json
- Removes the 'triggers' from the 'capabilities' as it causes errors when used with paconn tool.
- Broke out TimeZone schema to be different when used in request and responses.
- Remove path prefixes "/actions/{family}/" to match with other connectors.
- Fix Open Api warnings
- Fix response of CompleteTask_V2
---
> [OutlookTasks] fix capabilities and timezone data types

- certified-connectors/Aquaforest PDF Connector/apiDefinition.swagger.json
- certified-connectors/Connect2All/apiDefinition.swagger.json
- certified-connectors/HotProfile/apiDefinition.swagger.json
- certified-connectors/PDF4me/apiDefinition.swagger.json
- certified-connectors/PDF4me/apiProperties.json
- certified-connectors/Planner/apiProperties.json
- certified-connectors/Robolytix/apiDefinition.swagger.json
- certified-connectors/Scrive eSign/apiDefinition.swagger.json
- certified-connectors/TRIGGERcmd/apiDefinition.swagger.json
- certified-connectors/WebMerge/apiDefinition.swagger.json
- certified-connectors/WorkSpan/apiDefinition.swagger.json
Based on new schema cleanup, these connectors have small fixes to clean them up so they comply with the supported and normalized schemas.
> [Connect2All,HotProfile,PDF4me,Robolytix,ScriveESign,TRIGGERcmd,WebMerge,WorkSpan] Fix swaggers of various connectors

- custom-connectors/Facebook/apiDefinition.swagger.json
Publish_pages is deprecated from FB end
Reference: https://developers.facebook.com/docs/facebook-login/permissions
---
> (Azure CXP) Fixing the Facebook Swagger File

- certified-connectors/Poka/apiDefinition.swagger.json
> Poka - Make the language field mandatory. (Update apiDefinition.swagger)

- certified-connectors/timeghost/apiProperties.json
- certified-connectors/tyntec Portability Check/README.md
- certified-connectors/tyntec Portability Check/apiDefinition.swagger.json
- certified-connectors/tyntec Portability Check/apiProperties.json
> Tyntec portability check

- certified-connectors/Peltarion/apiDefinition.swagger.json
- certified-connectors/Peltarion/apiProperties.json
> Set url/token with policy

- tools/paconn-cli/paconn/operations/download.py
- tools/paconn-cli/paconn/operations/json_keys.py
> Save connectionParameterSet on custom connector download

- certified-connectors/PDF Blocks/apiDefinition.swagger.json
> line_1 in add_watermark is not longer required

- certified-connectors/FORCAM FORCE Bridge/apiDefinition.swagger.json
Added the property "objectID" to process data violation trigger to allow a further use case.
---
> Extend properties

- certified-connectors/Ubiqod by Skiply/apiDefinition.swagger.json
Follow the recommandation of Srikanth: please replace the "default" responses with expected status codes, otherwise users may see errors about incorrect schema instead of real error responses from your service in OpenAPI mode.
---
> Replace default responses by expected status codes

- certified-connectors/Dokobit Portal/apiDefinition.swagger.json
- certified-connectors/Dokobit Portal/readme.md
> Dokobit Portal: status signed_file type fix

- certified-connectors/VirusTotal/apiDefinition.swagger.json
> virtustotal - Change file name to file path

- certified-connectors/Impexium/apiProperties.json
> Update Icon brand color

- certified-connectors/Docurain/apiDefinition.swagger.json
> Fix error http status code and error response type.

- certified-connectors/Connective eSignatures/apiDefinition.swagger.json
- certified-connectors/Connective eSignatures/apiProperties.json
Add the ability to use a configurable host url so customers can connect to their own Connective eSignatures environment
---
> [IMPROVEMENT] Connective, use urlTemplate for configurable url

- certified-connectors/Formstack Documents/apiProperties.json
> Formstack Documents iconBrandColor change

- certified-connectors/HitHorizons/apiDefinition.swagger.json
- certified-connectors/HitHorizons/apiProperties.json
- certified-connectors/HitHorizons/readme.md
> Add HitHorizons connector

- certified-connectors/Flotiq/apiProperties.json
Please accept the update for icon brand color, as required in the ISV step of the certification process.
> Update icon brand color for certification

- certified-connectors/Way We Do/apiDefinition.swagger.json
Additional property on payload
---
> fix: Way We Do connector updates

- certified-connectors/Planner/apiDefinition.swagger.json
Planner now supports 25 labels in total. This change adds labels 7-25 to the AppliedCategories schema.
This will affect GetTask_Response_V2, UpdateTask_Request_V3 and CreateTask_Request_V3
---
> Planner - add support for all 25 categories

- custom-connectors/HR Cloud/README.md
- custom-connectors/HR Cloud/apiDefinition.swagger.json
- custom-connectors/HR Cloud/apiProperties.json
> HR Cloud Power Automate connector

- certified-connectors/Connect2All/apiDefinition.swagger.json
- certified-connectors/Connect2All/apiProperties.json
> Added batch trigger functionality

- certified-connectors/Lang-ai/apiDefinition.swagger.json
- certified-connectors/Lang-ai/apiProperties.json
- certified-connectors/Lang-ai/readme.md
> Upload Lang.ai Connector

- independent-publisher-connectors/readme.md
Missing hyperlink to the manifesto.
https://github-wiki-see.page/m/microsoft/PowerPlatformConnectors/wiki/Independent-Publisher-Connector-Group-%22Manifesto%22
---
> Missing hyperlink

- independent-publisher-connectors/readme.md
> Added 2 best practice callouts from the retro

- tools/paconn-cli/paconn/operations/json_keys.py
- tools/paconn-cli/paconn/operations/upsert.py
> Adjustment for multi-auth with OAuth.

- tools/paconn-cli/README.md
> Update the paconn tool readme due to public preview

- certified-connectors/IronDefense/Readme.md
- certified-connectors/IronDefense/apiDefinition.swagger.json
- certified-connectors/IronDefense/apiProperties.json
> Add IronDefense custom connector for certification

- independent-publisher-connectors/Yelp/apiDefinition.swagger.json
- independent-publisher-connectors/Yelp/apiProperties.json
- independent-publisher-connectors/Yelp/readme.md
> Yelp v1.1 (Independent Publisher)

- certified-connectors/SmartDialog/apiDefinition.swagger.json
> Added additional fields to SendMessage methods

- certified-connectors/DocuSign/apiDefinition.swagger.json
---
- [x ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.
If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing …
> Fix typo for Recipient Type

- certified-connectors/RescoCloud/README.md
- certified-connectors/RescoCloud/apiDefinition.swagger.json
- certified-connectors/RescoCloud/apiProperties.json
> 14793 native trigger actions from resco cloud

- certified-connectors/Connective eSignatures/Readme.md
- certified-connectors/Connective eSignatures/apiDefinition.swagger.json
- added missing properties `reassignEnabled` & `actionUrlExpirationPeriodInDays` to two methods
- fixed return property type from `boolean` to `integer` for `pageNumber`
- fixed return schema for `DownloadPackage`
- added missing method `DownloadDocumentFromPackage`
---
> Connective eSignatures bug fixes

- certified-connectors/Plumsail Forms/Readme.md
- certified-connectors/Plumsail Forms/apiDefinition.swagger.json
> Removed download attachment action

- independent-publisher-connectors/openFDA Drug/apiDefinition.swagger.json
- independent-publisher-connectors/openFDA Drug/apiProperties.json
- independent-publisher-connectors/openFDA Drug/readme.md
> openFDA Drug (Independent Publisher)

- independent-publisher-connectors/RestCountries/apiDefinition.swagger.json
- independent-publisher-connectors/RestCountries/apiProperties.json
- independent-publisher-connectors/RestCountries/readme.md
---
This is a custom connector to get all the countries lists and its relevant information using an open-source API restcountries.com
This would be useful where we need to create a dropdown to select the country and get is currency, language, timezone, etc also. 
Screenshot of actions in Flow
Screenshot of  Test operations section within the Custom Connector UI
Let me know if any changes are required.
> Rest Countries (Independent Publisher)

- README.md
I gave the `README.md` a bit of polish since it contained dead links, typos, unnecessary whitespace, and other hiccups. However, there is still lots of room for improvement.
—Sebastian
> README.md polish

- certified-connectors/CognitiveServicesTextAnalytics/Readme.md
- certified-connectors/CognitiveServicesTextAnalytics/apiDefinition.swagger.json
Following up "Text Analytics" service rename and renaming connector display name (and some descriptions) accordingly.
> Renamed 'Text Analytics' connector to 'Language Service'

- tools/paconn-cli/README.md
- tools/paconn-cli/paconn/operations/download.py
Power Platform Connectors CLI Update
This pull request will allow for a more consistent download experience and allow for better ALM by ensuring that custom connectors can be downloaded even if the files already exist.  Also updates the documentation which had no mention of the overwrite argument.
Issue: User cannot download connector files with the --overwrite argument unless they also supply the --destination argument. If they attempt to download the connector without the --destination argument the following error always appears, "{connectorid} directory already exists. Please remove the directory before continuing."
New Experience
* paconn download; If directory is found user is provided option to overwrite files within connectionid directory.
* paconn download --overwrite;  If …
> More consistent download experience for overwrite

- certified-connectors/SmartCOMM On Demand Doc-Gen/Readme.md
- certified-connectors/SmartCOMM On Demand Doc-Gen/apiDefinition.swagger.json
- certified-connectors/SmartCOMM On Demand Doc-Gen/apiProperties.json
> Submit SmartCOMM On Demand Doc-Gen for certification

- certified-connectors/DocuSignDemo/apiDefinition.swagger.json
- certified-connectors/DocuSignDemo/script.csx
---
- [ x] I validated the swagger file, …
> Update security parameter for webhook response operation

- certified-connectors/sms77io/apiDefinition.swagger.json
> sms77io: add definition StatusJsonResponse

- certified-connectors/ProcessStreet/apiDefinition.swagger.json
> Process Street - Fixing webhook deletion

- independent-publisher-connectors/RegEx Matching/apiDefinition.swagger.json
Changed input type from  integer to string for one of the operations
---
> RegEx Matching (Independent Publisher)

- certified-connectors/sms77io/apiDefinition.swagger.json
- [ x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. …
> make Status always return JSON

- certified-connectors/RegexFlow Regular Expression/apiDefinition.swagger.json
- certified-connectors/RegexFlow Regular Expression/apiProperties.json
- certified-connectors/RegexFlow Regular Expression/readme.md
> initial commit - RegexFlow Regular Expression

- certified-connectors/Meisterplan/apiDefinition.swagger.json
- the definied securityDefinitions caused the issue that the authorization header was not added to the requests resulting in 401 unauthorized results
> Meisterplan Connector: Removed securityDefinitions from swagger json

- certified-connectors/Converter by Power2Apps/Readme.md
- certified-connectors/Converter by Power2Apps/apiDefinition.swagger.json
- certified-connectors/Converter by Power2Apps/apiProperties.json
> Added new action

- certified-connectors/secplugs/apiDefinition.swagger.json
- certified-connectors/secplugs/apiProperties.json
- certified-connectors/secplugs/readme.md
> Typos, rewording and remaining branding changes

- certified-connectors/Morf/Readme.md
- certified-connectors/Morf/apiDefinition.swagger.json
- certified-connectors/Morf/apiProperties.json
---
- `basePath` was modified but the URI of the API was not. Both `basePath` and the `render` operation `paths` properties were updated accordingly.
> Add transformJsonata operation to Morf connector

- certified-connectors/PartnerCenterReferrals/apiDefinition.swagger.json
> Partner Center connector - new fields and deal registration actions

- certified-connectors/Plumsail Forms/apiDefinition.swagger.json
> Post method for downloading attachments has been replaced with Get

- certified-connectors/Maximizer/apiDefinition.swagger.json
> removed externalDocs which is not supported currently

- independent-publisher-connectors/Atlassian Jira/apiProperties.json
- independent-publisher-connectors/Brønnøysundregistrene/apiProperties.json
- independent-publisher-connectors/Care Quaility Comission For England/apiProperties.json
- independent-publisher-connectors/ChuckNorris.io/apiProperties.json
- independent-publisher-connectors/DPIRD Radar/apiProperties.json
- independent-publisher-connectors/DPIRD Science/apiProperties.json
- independent-publisher-connectors/DPIRD Weather/apiProperties.json
- independent-publisher-connectors/Discord/apiProperties.json
- independent-publisher-connectors/EONET by NASA/apiProperties.json
- independent-publisher-connectors/Etsy/apiProperties.json
- independent-publisher-connectors/Festivo/apiProperties.json
- independent-publisher-connectors/Hashify/apiProperties.json
- independent-publisher-connectors/MyHospitals by AIHW/apiProperties.json
- independent-publisher-connectors/OpenWeather/apiProperties.json
- independent-publisher-connectors/Placedog/apiProperties.json
- independent-publisher-connectors/Revue/apiProperties.json
- independent-publisher-connectors/Secure Code Warrior/apiProperties.json
- independent-publisher-connectors/Spotify/apiProperties.json
- independent-publisher-connectors/Synthesia/apiProperties.json
- independent-publisher-connectors/The Lord of the Rings/apiProperties.json
- independent-publisher-connectors/Toggl Plan/apiProperties.json
- independent-publisher-connectors/U.K. Government Bank Holidays/apiProperties.json
- independent-publisher-connectors/XSOAR/apiProperties.json
- independent-publisher-connectors/Yelp/apiProperties.json
- independent-publisher-connectors/icanhazdadjoke/apiProperties.json
According to the guidelines, the iconBrandColor for independent connectors must be `#da3b01`.
> Fix value of iconBrandColor for independent connectors

- independent-publisher-connectors/LanguageTool/apiDefinition.swagger.json
- independent-publisher-connectors/LanguageTool/apiProperties.json
- independent-publisher-connectors/LanguageTool/readme.md
> LanguageTool (Independent Publisher)

- certified-connectors/OpenText Core Share/apiDefinition.swagger.json
- certified-connectors/OpenText Core Share/apiProperties.json
- certified-connectors/OpenText Core Share/readme.md
I'm not exactly sure why nor how, but it apparently there is no Core Share folder nor branch in GitHub while even though it is a certified connector in the Microsoft store (https://learn.microsoft.com/en-gb/connectors/opentextcoreshare/)
> OpenText Core Share v1.1

- certified-connectors/Blackbaud SKY Add-ins/script.csx
> Provide useful error message for PATCH support
